// TODO: add at least 2 explorers per coin

const explorerList = {
  SAFE: 'http://www.safeexplorer.ru',
  MSHARK: 'http://MSHARK.explorer.ipv6admin.com',
  REVS: 'http://revs.explorer.ipv6admin.com',
  SUPERNET: 'http://SUPERNET.explorer.ipv6admin.com',
  DEX: 'http://DEX.explorer.ipv6admin.com',
  PANGEA: 'http://PANGEA.explorer.ipv6admin.com',
  JUMBLR: 'http://JUMBLR.explorer.ipv6admin.com',
  BET: 'http://BET.explorer.ipv6admin.com',
  CRYPTO: 'http://CRYPTO.explorer.ipv6admin.com',
  HODL: 'http://HODL.explorer.ipv6admin.com',
  SHARK: 'http://SHARK.explorer.ipv6admin.com',
  BOTS: 'http://BOTS.explorer.ipv6admin.com',
  MGW: 'http://MGW.explorer.ipv6admin.com',
  WLC: 'http://WIRELESS.explorer.ipv6admin.com',
  CHIPS: 'http://CHIPS1.explorer.ipv6admin.com',
  COQUI: 'https://explorer.coqui.cash',
  MNZ: 'https://www.mnzexplorer.com',
  BTCH: 'http://www.btch.host',
  BTC: 'https://blockchain.info',
  HUSH: 'https://explorer.myhush.org',
  PIZZA: 'http://pizza.safecoinchainz.info',
  BEER: 'http://beer.safecoinchainz.info',
  NINJA: 'https://explorer.fund.ninja',
  VOTE2018: 'http://88.99.226.252',
  QTUM: 'https://explorer.qtum.org',
  DNR: 'http://denarius.name',
  LTC: 'https://live.blockcypher.com/ltc',
  DOGE: 'https://live.blockcypher.com/doge',
  DASH: 'https://live.blockcypher.com/dash',
  MONA: 'https://bchain.info/MONA',
  VIA: 'https://explorer.viacoin.org',
  VTC: 'http://explorer.vertcoin.info',
  NMC: 'https://namecha.in',
  DGB: 'https://digiexplorer.info',
  CRW: 'http://ex.crownlab.eu',
  BTG: 'https://btgexplorer.com',
  BCH: 'https://bitcoincash.blockexplorer.com',
  ZCL: 'http://explorer.zclmine.pro',
  ZMY: 'https://myriadexplorer.com',
  BTX: 'http://explorer.bitcore.cc',
  BTCZ: 'https://explorer.bitcoinz.site',
  HODLC: 'http://www.fuzzbawls.pw/explore/HOdlcoin/tx.php?tx=',
  SIB: 'https://chain.sibcoin.net/en/tx/',
  ZEC: 'https://explorer.zcha.in/transactions/',
  BLK: 'https://explorer.coinpayments.net/transaction.php?chain=4&hash=',
  ARG: 'https://prohashing.com/explorer/Argentum/',
  FAIR: 'https://chain.fair.to/transaction?transaction=',
};

export default explorerList;