export const LANG_RU = {
  'WALLETS_INFO': {
    'ADDRESS': 'IP Адрес',
    'ADDRESS_LOCAL': 'Локальный IP Адрес',
    'SERVICES': 'Сервисы',
    'VERSION': 'Версия',
    'SUBVERSION': 'Версия',
    'WHITELISTED': 'Белый список',
    'INBOUND': 'Входящий',
    'TIME_OFFSET': 'Временной сдвиг',
    'PING_TIME': 'Время пинга',
    'CONNECTION_TIME': 'Время подключения',
    'LAST_SEND': 'Последняя отправка',
    'LAST_RECEIVED': 'Последнее получение',
    'DATA_SENT': 'Данные отправлены',
    'DATA_RECEIVED': 'Данные получены',
    'BAN_SCORE': 'Штрафные очки',
    'STARTING_HEIGHT': 'Начальная высота',
    'SYNCED_HEADERS': 'Синхронизировано заголовков',
    'SYNCED_BLOCKS': 'Синхронизировано блоков',
    'NETWORK_TOTALS': 'Данные сети',
    'TIME': 'Время',
    'PEERS': 'Участники',
    'LOADING': 'Загрузка...',
  },
  'IMPORT_KEY': {
    'IMPORT': 'Импортировать',
    'IMPORT_KEY': 'Импортировать ключ',
    'TWO_FORMS_BELOW_P1': 'Две формы ниже позволяют Вам импортировать',
    'TWO_FORMS_BELOW_P2': 'парольную фразу (seed) или',
    'TWO_FORMS_BELOW_P3': 'ключ',
    'PASSPHRASE': 'Парольная фраза / seed',
    'NOTICE': 'Уведомление',
    'NOTICE_DESC': 'импорт парольной фразы приведет к полному сканированию блокчейна',
    'SAFE_RESCAN_WARNING_TIME': 'Процесс сканирования блокчейна может занять продолжительное время',
    'SHOW_ADDRESS_AND_WIF': 'Показать адрес и ключ (WIF)',
    'ADDRESS': 'Адрес',
    'OR': 'или',
    'TRIGGER_RESCAN': 'Сканирование',
    'RESCAN_TIP': 'Используйте эту опцию, если хотите произвести полное сканирование после импорта ключа. Если у Вас несколько адресов произведите поочерёдное импортирование и включите эту опцию при импорте последнего.',
    'WIF_KEY': 'ключ (WIF)',
    'IMPORT_AND_RESCAN': 'Импорт и рескан',
  },
  'CLAIM_INTEREST': {
    'SHOW_ZERO_INTEREST': 'Показывать нулевые проценты',
    'REQ_P1': 'Требования к начислению процентов',
    'REQ_P2': 'отправка средств была произведена минимум 1 час назад поле locktime установлено, и начисление больше, чем',
    'CLAIM_INTEREST': 'Зачислить @template@ проценты',
    'LOADING': 'Загружаем данные процентов',
    'NO_DATA': 'Нет данных',
    'TIP': 'Tip',
    'NOTICE': 'Уведомление',
    'TIP_DESC': 'не пытайтесь зачислить процент меньше 0.01 SAFE. Стоимость транзакции может оказаться больше или равна сумме процентов.',
    'NATIVE_INTEREST_CHANGE_DESC': 'Вероятно, что проценты будут зачислены как отдельная транзакция на новый SAFE-адрес.',
  },
  'ABOUT': {
    'SAFEWALLET_WALLET': 'Бумажник Safewallet',
    'ABOUT_SAFEWALLET': 'О Safewallet',
    'SAFEWALLET_MODES': 'Бумажник Safewallet - приложение, позволяющее Вам управлять несколькими кошельками криптовалют. ' +
                     'Вы можете настроить кошелёк для работы в нескольких режимах:',
    'NATIVE_MODE_DESC': 'Доступно для нескольких криптовалют, аналогично \'Full Mode\' но обладает расширенной функциональностью.',
    'SAFEWALLET_CAPABILITIES': 'Safewallet включает в себя следующие возможности:',
    'BARTER_DEX_DESC': 'Простой обмен криптовалют через shapeshift-образный сервис.',
    'SAFEWALLET_NOTE': 'Пояснение: Safewallet Кошелёк всё ещё в разработке. ' +
                    'Он безопасен в использовании, но Вы должны делать резервные копии. ' +
                    'Мы не рекомендуем Вам использовать его в качестве основного кошелька криптовалют.',
    'TESTERS': 'Тестирование',
    'TESTERS_P1': 'Вы можете помочь нам сделать Safewallet лучше. ',
    'TESTERS_P2': 'Скачайте и установите последний релиз,',
    'TESTERS_P3': 'сообщайте о любых ошибках найденных в приложении команде разработчиков.',
    'TESTERS_P4': 'Ваша помощь незаменима!',
    'SAFEWALLET_DAPPS': 'Safewallet также поддерживает следующие приложения:',
    'JUMBLR_DESC': 'Децентрализованный Bitcoin Tumbler, для обеспечения конфиденциальности и снижения комиссии.',
    'BARTER_DEX_DESC_ALT': 'Децентрализованный обменник криптовалют.',
    'CHANNEL': 'channel',
    'GET_AN_INVITE': 'Получите приглашение',
    'GET_AN_INVITE_P2': 'в наш чат, если Вы еще не зарегистрированы там'
  },
  'API': {
    'DAEMON_IS_STILL_RUNNING': 'сервис кошелька все еще работает. Если вы хотите полностью остановить его - в следующий раз используйте значок остановки.',
    'CONN_ERROR': 'Ошибка подключения',
    'SAFE_PASSIVE_ERROR': 'Пожалуйста, убедитесь, что safecoind запущен',
    'ERROR_SM': 'ошибка',
    'ADDRESS_ALREADY_REG': 'Адрес уже зарегистрирован',
    'COULDNT_COPY_ADDRESS': 'Не могу скопировать адрес в буфер',
    'COULDNT_CREATE_SEED': 'Не могу создать новый wallet seed',
    'WALLETDAT_MISMATCH': 'Ваш файл wallet.dat не соответствует блокчейну. Пожалуйста, перезапустите кошелёк с параметром -reindex.',
    'PEER_ADDED': 'Пир добавлен',
    'ADDNODE_ALREADY_PENDING': 'Подключение к ноде уже ожидается',
    'PEER_ALREADY_CONN': 'Пир уже подключен ',
    'ADDNODE_NEEDS_COIN': 'для Addnode, демон монеты должен быть активен',
    'PRIVKEY_IN_WALLET': 'Приватный ключ уже добавлен',
    'ILLEGAL_PRIVKEY': 'Ошибочный приватный ключ',
    'NO_ACTIVE_COIN': 'Нет активных монет',
  },
  'INDEX': {
    'WALLET_OFFLINE': 'Safewallet не может подключиться к Интернету.',
    'OFFLINE': 'Оффлайн',
    'TOGGLE_COIN_CONTEXT_MENU': 'Переключить контекстное меню монеты',
    'TOP_MENU': 'Top menu',
    'ERROR_READING': 'Ошибка чтения',
    'SHOW': 'Показать',
    'SPV_SERVER_IP': 'Сервер IP',
    'SPV_SERVER_PORT': 'Сервер Port',
    'SPV_SERVER_CON_TYPE': 'Тип подключения',
    'COIND_DOWN_MODAL_ERROR': ' debug.log пустой, похоже, что демон не смог корректно запуститься. Попробуйте повторить.',
    'SPV_MODE': 'Lite (SPV) Режим',
    'PROGRESS_RESCANNING_BLOCKS': '(Сканирование блоков)',
    'BLOCKS': 'Блок',
    'PLEASE_WAIT_UNTIL_RESCAN_FINISHED': 'Пожалуйста, дождитесь окончания процесса сканирования блоков',
    'VERIFYING_BLOCKS': 'Проверка блоков',
    'ALL': 'Все',
    'NATIVE_ONLY_MODE': 'Нативный режим',
    'NORMAL_MODE': 'Обычный режим ',
    'T_FUNDS': 'Публичные средства',
    'HASH': 'Хэш',
    'SYNC_IN_PROGRESS': 'Синхронизация в процессе.',
    'UI_UPDATE_DOWNLOADED': 'UI обновление загружено. Проверяется',
    'UI_UPDATED': 'UI был обновлён!',
    'UI_UPDATE_ERROR': 'Ошибка во время проверки файла обновления! Попробуйте ещё раз.',
    'CHECKING_UI_UPDATE': 'Проверяю наличие обновлений UI',
    'NEW_UI_UPDATE': 'Вышла новая версия UI',
    'YOU_HAVE_LATEST_UI': 'У Вас установлена последняя версия UI',
    'DOWNLOADING_UI_UPDATE': 'Загружаю UI обновление',
    'LAST_50_LINES': 'последние 50 строк',
    'IS_DOWN': 'недоступен',
    'REINDEX': 'переиндексация',
    'RESCAN': 'сканирование',
    'BACKGROUND_PROCESS': 'фоновый процесс',
    'NONE': 'none',
    'DAEMON_PARAM': 'Параметры службы',
    'FILTER_BY_ADDRESS': 'Сортировать по адресу',
    'RESCANNING_LAST_BLOCKS': 'Сканируем последние блоки...',
    'NO_DATA_AVAILABLE': 'Данные недоступны',
    'LOADING': 'Загружается',
    'ACTIVATING_SM': 'активация',
    'DL_BLOCKS': 'загрузка блоков',
    'RESCAN_SM': 'сканирование блоков',
    'REINDEX': 'переиндексация блоков на диске',
    'BLOCKS_SM': 'блок',
    'LOADING_BLOCKS': 'Загрузка данных, подождите...',
    'WEAK_SEED': 'Слабая кодовая фраза!',
    'YOUR_SEED_MUST_CONTAIN': 'Ваша кодовая фраза должна соответствовать следующим требованиям:',
    'YOUR_SEED_MUST_CONTAIN1': '- как минимум 1 заглавная буква',
    'YOUR_SEED_MUST_CONTAIN2': '- как минимум 1 цифра',
    'YOUR_SEED_MUST_CONTAIN3': '- как минимум 1 специальный символ ',
    'YOUR_SEED_MUST_CONTAIN4': '- минимум 10 символов',
    'YOUR_SEED_MUST_CONTAIN5': '- максимум 100 символов',
    'EXECUTE': 'Выполнить',
    'TYPE_CLI_CMD': 'Введите CLI-совместимую команду',
    'COIN': 'Монета',
    'UPDATE': 'Обновление',
    'UI_UPDATE': 'UI update',
    'CHECK_FOR_UPDATE': 'Проверить обновления',
    'UPDATE_UI_NOW': 'Обновить UI сейчас',
    'BINS_UPDATE': 'Обновление исполняемых файлов',
    'UPDATE_BINS_NOW': 'Обновить исполняемые файлы',
    'CLI_SELECT_A_COIN': 'Выберите монету и введите CLI-совместимую команду',
    'CLI_NATIVE_COIN': 'Выберите монету',
    'IMPORT': 'Import',
    'CHECK': 'Check',
    'VALIDATE': 'Validate',
    'COPY_TO_CLIPBOARD': 'Скопировать в буфер',
    'EMPTY_DEBUG_LOG': 'Debug.log пустой',
    'RESTART': 'Перезапуск',
    'WALLET_INFO': 'Информация о кошельке',
    'ADD_COIN': 'Добавить монету',
    'STOP': 'Стоп',
    'START': 'Старт',
    'ACTIVE_ADDRESS': 'активный адрес',
    'NO_DATA': 'История недоступна',
    'LOADING_HISTORY': 'Загружаем историю транзакций',
    'CLOSE': 'Зарыть',
    'SHOW': 'Show',
    'SHOWING': 'Showing',
    'OF': 'of',
    'TO_ALT': 'to',
    'SEARCH': 'Search',
    'PREVIOUS': 'Предыдущий',
    'NEXT': 'Следующий',
    'ENTRIES_SM': 'entries',
    'SYNC_ERR_BLOCKS': 'Подключаемся к пирам...',
    'SELECT_A_COIN': 'Выберите монету для добавления в Safewallet',
    'WALLETS': 'Кошельки',
    'ACTIVATE_COIN': 'Активировать монету',
    'WELCOME_PLEASE_ADD': 'Добро пожаловать.',
    'WELCOME_PLEASE_ADD2': 'Пожалуйста, добавьте монету для старта.',
    'SELECT_SEED_TYPE': 'Please select compatible wallet seed type',
    'SELECT': '-Выбрать-',
    'NATIVE_MODE': 'Native режим',
    'NATIVE_MODE_DESC1': 'Этот режим доступен только для: SAFECOIN Coin. ' +
                         'Этот режим',
    'NATIVE_MODE_DESC2': 'загружает полный блокчейн.',
    'NATIVE_MODE_DESC3': 'только этот режим позволяет Вам делать',
    'NATIVE_MODE_DESC4': 'Z Транзакции',
    'NATIVE_MODE_DESC5': 'Приватные Транзакции',
    'CLOSE': 'Закрыть',
    'PLEASE_USE': 'Please use either',
    'OR': 'или',
    'TO_USE': 'to use',
    'WELCOME_LOGIN': 'Добро пожаловать.',
    'WELCOME_LOGIN2': 'Пожалуйста, авторизуйтесь',
    'WALLET_SEED': 'Парольная фраза / ключ (WIF)',
    'SIGN_IN': 'Войти',
    'CREATE_WALLET': 'Создать новый кошелёк',
    'LOGIN_ANOTHER_WALLET': 'Войти в другой кошелёк',
    'CONFIRM_SEED': 'Подтвердите парольную фразу',
    'REGISTER': 'Register',
    'BACK_TO_LOGIN': 'Back to Login',
    'TOGGLE_NAV': 'Toggle navigation',
    'TOGGLE_SEARCH': 'Toggle Search',
    'TOGGLE_MENUBAR': 'Toggle menubar',
    'SETTINGS': 'Настройки',
    'LOGOUT': 'Завершить сеанс',
    'DASHBOARD': 'Dashboard',
    'WALLET_SETTINGS': 'Настройки бумажника',
    'SAFE_WALLET': 'Кошелёк Safecoin',
    'ZC_WALLET': 'Кошелёк Zcash',
    'ACTIVE_COINS': 'Активировать Монеты',
    'TRANSACTIONS': 'Транзакции',
    'SEND': 'Отправить',
    'RECEIVE': 'Получить',
    'BUNDLES': 'Группы',
    'BALANCES': 'Балансы',
    'BALANCE': 'Баланс',
    'VALIDATED': 'Подтверждено',
    'NO_WALLET_CAPS': 'НЕ ВЫБРАН КОШЕЛЁК',
    'PLEASE_SELECT_A_WALLET': 'Пожалуйста, выберите кошелек из списка активных монет слева.',
    'ADDRESS': 'Адрес',
    'MY': 'Мой',
    'COPY': 'копировать',
    'INTEREST_EARNED': 'Начисленные проценты',
    'TOTAL_BALANCE': 'Баланс Итого',
    'GET_BALANCE': 'Узнать баланс',
    'REFRESH': 'Обновить',
    'LIST_UNSPENT': 'Список не потраченных',
    'LIST_TRANSACTIONS': 'Список транзакций',
    'TRANSACTION_HISTORY': 'История транзакций',
    'DIRECTION': 'Направление',
    'CONFIRMATIONS': 'Подтверждения',
    'AMOUNT': 'Количество',
    'TIME': 'Время',
    'DEST_ADDRESS': 'Адрес получения',
    'TX_DETAIL': 'Подробности Tx',
    'FILL_SEND_FORM': 'Заполните форму отправки',
    'FILL_SEND_DETAILS': 'Укажите детали перевода',
    'CONFIRMING': 'Подтверждение',
    'CONFIRM_DETAILS': 'Убедитесь в правильности данных',
    'PROCESSING_TX': 'Обрабатываем Tx',
    'PROCESSING_DETAILS': 'Processing and showing details',
    'SEND_FROM': 'Отправить С',
    'SEND_TO': 'Отправить На',
    'FEE': 'Комиссия',
    'TOTAL': 'Итого',
    'AMOUNT_SM': 'кол-во',
    'DONT_SEND': 'Не отправлять транзакцию - показать мне подписанный текст транзакции.',
    'TO': 'Кому:',
    'TX_FEE_REQ': 'Комиссия транзакции (требуется майнерами)',
    'FROM': 'От кого:',
    'CONFIRM': 'Подтвердить',
    'BACK': 'Назад',
    'TRANSACTION_RESULT': 'Результат транзакции',
    'KEY': 'Ключ',
    'VALUE': 'Значение',
    'INFO': 'Информация',
    'MAKE_ANOTHER_TX': 'Еще транзакция',
    'RECEIVING_ADDRESS': 'Адреса получения',
    'TYPE': 'Тип',
    'INTEREST': 'Проценты',
    'ACTIVATING_CHAIN': 'Активация лучшей цепи блоков',
    'SAFE_STARTED': 'Служба Safecoind была запущена.<br>' +
                    'Пожалуйста, подождите, пока лучшая цепь будет активирована.<br>' +
                    'Подсказка: в случае, если синхронизация зависла  - перезапустите кошелёк.',
    'CONNECTIONS': 'Подключения',
    'TRANSPARENT_BALANCE': 'Публичный баланс',
    'Z_BALANCE': 'Приватный (Z) баланс',
    'INTEREST_EARNED': 'Начислены Проценты',
    'ZT_BALANCE': 'Общий (Z+T) Баланс',
    'GET_NEW_ADDRESS': 'Создать новый адрес',
    'TRANSPARENT_ADDRESS': 'Публичный адрес',
    'PRIVATE_Z_ADDRESS': 'Приватный адрес',
    'OPERATIONS_STATUSES': 'Состояние операций',
    'STATUS': 'Статус',
    'RESULT': 'Результат',
    'WALLET_INFO': 'Информация о кошельке',
    'WALLET_VERSION': 'Версия кошелька',
    'UNCONFIRMED_BALANCE': 'Неподтверждённый баланс',
    'IMMATURE_BALANCE': 'Незрелый баланс',
    'TOTAL_TX_COUNT': 'Общее число транзакций',
    'INFO': 'Информация',
    'VERSION': 'Версия',
    'PROTOCOL_VERSION': 'Версия протокола',
    'NOTARIZED': 'Нотариальные узлы',
    'BLOCKS': 'Блоков',
    'DIFFICULTY': 'Сложность',
    'PAY_TX_FEE': 'Pay Transaction Fee',
    'RELAY_FEE': 'Relay Fee',
    'ERRORS': 'Errors',
    'ADD_NODE': 'Add Node',
    'USE_THIS_SECTION': 'Use this section to check if the node IP you wish to add is already active as peer of your coin:',
    'SELECT_COIN': 'Select Coin',
    'CHECK_NODES': 'Check Nodes',
    'USE_THIS_SECTION_PEER': 'Use this section to add a peer IP to a selected coin:',
    'WALLET_BACKUP': 'Wallet Backup',
    'FIAT_CURRENCY': 'Fiat Currency',
    'EXPORT_KEYS': 'Export Keys',
    'ONLY_ACTIVE_WIF_KEYS': 'Only the active coin wallet WIF keys will be shown here.<br>' +
                            'You can use these WIF keys to import to another coin wallets.',
    'PLEASE_KEEP_KEYS_SAFE': 'Please keep these keys extra safe and secure.',
    'PASSPHRASE': 'Passphrase',
    'GET_WIF_KEYS': 'Get WIF Keys',
    'IMPORT_KEYS': 'Import Keys',
    'IMPORT_KEYS_DESC_P1': 'This section allows you to import private key of all iguana supported coins, Assetchain, Geckochain, or PAXchain by the wallet.',
    'IMPORT_KEYS_DESC_P2': 'It is not mandatory to have that coin active in the wallet for which you are executing import private key process.',
    'IMPORT_KEYS_DESC_P3': 'You\'ll also notice the private key you imported for one coin or chain will also be showing a new address in all other coin wallets\' receiving address section. ' +
               'It is normal.',
    'INPUT_PRIV_KEY': 'Input Private Key',
    'IMPORT_PRIV_KEY': 'Import Private Key',
    'EMPTY_PASSPHRASE_FIELD': 'Empty passphrase field',
    'WALLET_RESCAN_FINISHED': 'Wallet rescan is finished',
    'ADDRESS_IMPORTED': 'Address imported',
    'ADDRESS_IMPORTED_RESCAN_IN_PROGRESS': 'Address imported. Wallet rescan is in progress. Please wait until it is finished.',
    'DEBUG_LOG': 'Debug',
    'DEBUG_LOG_DESC': 'This section allows you to read last N lines from debug log file.',
    'DEBUG_LOG_LINES': 'Input number of lines to read',
    'TARGET': 'Target',
    'LOAD_DEBUG_LOG': 'Load debug log',
    'REFRESH_FUNDS': 'Refresh Funds',
    'INFO': 'Info',
    'ENTER': 'Enter',
    'ADDR_SM': 'address',
    'ACTIVATING': 'Activating',
    'QRCODE': 'Show QR code',
    'SCAN_QR_CODE': 'Scan QR Code',
    'SCAN_QRCODE_WEBCAM': 'Scan QR Code with webcam',
    'TOGGLE_ZERO_ADDRESSES': 'Toggle empty addresses',
    'NEXT_PAGE': 'Next Page',
    'PREVIOUS_PAGE': 'Previous Page',
    'CREATE_INVOICE': 'Create Invoice',
    'CREATE_INVOICE_QR': 'Create Invoice QR Code',
    'QR_CONTENT': 'QR Content',
    'CHOOSE_RECEIVING_ADDRESS': 'Choose Address',
    'SAVE_AS_IMAGE': 'Save as Image',
    'OPEN_TRANSACTION_IN_EPLORER': 'Open transaction in @template@ Explorer',
    'SWISSKNIFE': 'Поддержка',
    'SAFEVOTE': 'Safe Голосование',
    'TOOLS': 'Инструменты', 
  },
  'ATOMIC': {
    'RAW_OUTPUT': 'Raw вывод',
    'SUBMIT': 'Отправить',
    'INPUT_PLACEHOLDER': 'addr, txid, blockash и т.д.',
    'SELECT_COMMAND': 'Выберите команду',
  },
  'ADD_COIN': {
    'SYNC_ONLY': 'Только синхронизация',
    'SAVE_SELECTION': 'Сохранить выделенное',
    'LOAD_SELECTION': 'Загрузить выделенное',
    'ACTIVATE_ALL': 'Активировать всё',
    'ADD_ANOTHER_COIN': 'Добавить ещё монету',
    'ALREADY_ADDED': 'уже добавлено',
    'COIN_ALREADY_ADDED': 'Монета уже добавлена',
    'IN': 'в',
    'MODE': 'режим',
    'CRYPTO_CURRENCIES': 'Крипто валюты',
    'ASSETCHAINS': 'Assetchains',
    'FIAT_CURRENCIES': 'Фиатные валюты',
    'LITE': 'Lite',
    'LITE_MODE_DESC': 'Режим Lite не требует, загрузки цепочки блоков. Все данные запрашиваются с серверов Electrum. Режим Lite имеет более высокую задержку в сети по сравнению с обычным режимом.',
  },
  'JUMBLR': {
    'PASSPHRASE': 'Кодовая фраза',
    'PAUSE': 'Пауза',
    'RESUME': 'Продолжить',
    'STOP': 'Стоп',
    'TO_SM': 'кому',
    'ABOUT': 'О Jumblr',
    'JUMBLR_FUNCTIONS': 'Jumblr выполняет все локально, что означает, не требуется посредник для запутывания Ваших средств. ' +
                        'Весь процесс у Вас под контролем.',
    'TIP': 'Подсказка',
    'TIP_DESC': 'для достижения максимальной анонимности Jumble node на выделенном сервере (ноутбук или VPS), используйте отдельный IP-адрес для основного узла Jumblr',
    'PUBLIC_NODE': 'Публичные ноды',
    'PRIVATE_NODE': 'Приватные ноды',
    'DEPOSIT_ADDRESS': 'Адрес пополнения',
    'SECRET_ADDRESS': 'Секретный адрес',
    'DEPOSIT_FUNDS': 'Deposit funds',
    'HOW_TO_USE': 'Как пользоваться Jumblr',
    'CREATE_DEPOSIT_ADDRESS': 'Создайте адрес пополнения',
    'CREATE_SECRET_ADDRESS': 'Создайте секретный адрес',
    'SEND_FUNDS_TO_DEPOSIT': 'Отправьте средства на deposit адрес',
    'PLEASE_WRITE_DOWN_PASSPHRASE': 'Введите Вашу парольную фразу Jumblr и храните её в безопаcном месте.',
    'THIS_IS_YOUR_MAIN_RECOVERY': 'Это Ваша основная парольная фраза для восстановления.',
    'ALL_JUMBLR_ADDRESSES_CAN_BE': 'Все адреса Jumblr могут быть восстановлены по ней.',
    'DONT_USE_SMART_EDITORS': 'не используйте интеллектуальные редакторы для хранения вашей кодовой фразы, поскольку они, как правило, добавляют дополнительные символы.<br>Это может привести к несоответствию парольной фразы с исходной кодовой фразой.',
    'PASSPHRASE_COPIED': 'Парольная фраза скопирована',
    'CREATE_JUMBLR_DEPOSIT_ADDRESS': 'Создайте Jumblr адрес пополнения',
    'YOUR_JUMBLR_DEPOSIT_ADDRESS': 'Ваш Jumblr адрес пополнения',
    'JUMBLR_SECRET_DESC_P1': 'Jumblr секретные адреса используются для заключительной z -> t транзакций.',
    'JUMBLR_SECRET_DESC_P2': 'Чтобы позволить более крупным учетным записям получать конфиденциальность, поддерживаются до 777 секретных адресов.',
    'JUMBLR_SECRET_DESC_P3': 'Когда активируется этап z -> t, выбирается случайный секретный адрес из списка активных секретных адресов.',
    'JUMBLR_SECRET_DESC_P4': 'Чтобы добавить ещё набор секретных адресов, введите количество адресов ниже. Кодовая фраза ниже точно такая же, как вы видели на предыдущем шаге.',
    'JUMBLR_SECRET_DESC_P5': 'Ваша Jumblr парольная фраза для восстановления секретных адресов будет иметь следующий шаблон',
    'JUMBLR_SECRET_DESC_P6': 'Где XXX любое число от 001 до 777',
    'NUMBER_OF_SECRET_ADDR': 'Количество секретных адресов',
    'CREATE_JUMBLR_SECRET_ADDR': 'Создать Jumblr секретный адрес(а)',
    'SHOW_ADDRESS_LIST': 'Показать список адресов',
    'DEPOSIT_FORM_P1': 'Используйте форму ниже, чтобы отправить средства на Ваш jumblr адрес пополнения.',
    'DEPOSIT_FORM_P2': 'Вы так же можете отправить средства на jumblr адрес пополнения с любого внешнего сервиса или другого кошелька.',
    'IMPORT_SECRET_ADDRESS': 'Импортировать секретный адрес',
    'CHECK_FUNDS': 'Проверить средства',
    'SECRET_REGEN_DESC_P1': 'Для импорта секретного адреса Jmbrl, введите Вашу кодовую фразу Jumblr которую Вы получили при настройке Публичного узла.',
    'SECRET_REGEN_DESC_P2': 'Пример кодовой фразы',
    'SECRET_REGEN_DESC_P3': 'В форме ниже будет «регенерирован» секретный адрес Jumblr на основе введённой кодовой фразы.',
    'SECRET_REGEN_DESC_P4': 'После этого последнего шага ожидайте увидеть средства, обработанные и зачисленные на ваш адрес в течении двух дней.',
    'IMPORT_JUMLR_SECRET_ADDRESSES': 'Импорт секретных адресов Jumblr',
    'SHOW_ADDRESS_LIST': 'Показать список адресов',
    'NOTICE': 'ЭКСПЕРИМЕНТАЛЬНАЯ ВЕРСИЯ! ТОЛЬКО ДЛЯ ТЕСТИРОВАНИЯ!',
    'DESCRIPTION': 'Функция Jumblr экспериментальна и на данный момент включена только для тестирования и отладки. ' +
                   'Если вы участвуете в тестировании этой функции, используйте текущую версию Jumblr только с небольшими суммами.',
    'NEED_NATIVE': 'Требуется Нативный режим Safecoin',
    'TO_USE_JUMBLR': 'Чтобы использовать функцию Jumblr, вам необходимо активировать Safecoin в Нативном режиме.',
    'IF_YOU_ALREADY_RUNNING': 'Если вы уже используете Safecoin в режиме Basilisk или Полный Режим, закройте кошелек и снова перезапустите, чтобы запустить Safecoin в Нативном Режиме.',
    'THIS_SCREEN_DOESNT_REFRESH': 'Это окно не обновляется автоматически. ' +
                                  'Вам нужно нажать кнопку «Обновить» в правом верхнем углу окна, чтобы получить последние данные Jumblr.',
    'FEW_SECURITY_NOTES': 'Несколько примечаний по безопасности для вашей конфиденциальности и анонимности средств',
    'FEW_SECURITY_NOTES_DESC1': 'Jumblr адреса - это ваши личные адреса.',
    'FEW_SECURITY_NOTES_DESC2': 'НИКОМУ НЕ ПОКАЗЫВАЙТЕ Ваши Jumblr адреса.',
    'FEW_SECURITY_NOTES_DESC3': 'Jumblr адрес - это как ВАШ ПАРОЛЬ. Храните его в безопасности, надёжно и скрытно.',
    'FEW_SECURITY_NOTES_DESC4': 'Только ВЫ должны знать Ваши Jumblr адреса. Никто больше.',
    'FEW_SECURITY_NOTES_DESC5': 'Раскрытие Ваших Jumblr  адресов и совместное использование с кем-нибудь лишает смысла в использовании Jumblr, Ваши средства и транзакции не будут больше приватными.',
    'ACCESS_JUMBLR_FUNDS': 'Как получить доступ к своим Jumblr средствам',
    'ADDRESS_ACCESSIBLE_EASILY': 'Ваши Jumblr адреса легко доступны. Например, вы вошли в свой кошелек с кодовой фразой',
    'TO_ACCESS': 'Чтобы получить доступ к своим ресурсам Jumblr Вам необходимо выйти.',
    'START_SAFE': 'Запустить Safecoin в режиме Full или Basilisk.',
    'WORD_JUMBLR': 'Затем добавьте слово \'jumblr\' перед вашей фразой.',
    'SMALL_LETTERS': '"jumblr" все буквы маленькие .',
    'WHITE_SPACE': 'Пробел в конце "jumblr ".',
    'PER_EXAMPLE': 'Таким образом, согласно этому примеру, ваши Jumblr Адреса доступны:',
    'LOGIN_WITH_JUMBLR': 'Вы авторизовались с Вашей Jumblr кодовой фразой для доступа к Вашими Jumblr-средствам, и можете использовать их, так же как и любой адрес в кошельке.',
    'AGAIN_DONT_SHARE': 'И снова, НЕ ДЕЛИТЕСЬ СВОИМ JUMBLR АДРЕСОМ НИ КЕМ.',
    'USING_JUMBLR': 'Использование Jumblr',
    'RUN_SAFE': 'Запустите Safecoin в Native режиме',
    'LOGIN_SAFE': 'Авторизуйтесь используя свою кодовую фразу',
    'GO_TO': 'Откройте закладку Jumblr',
    'FIND_DEPOSIT_ADDR': 'Найдите там Ваш Депозитный адрес монеты, средства которой Вы хотите анонимизировать. (На начальном этапе поддерживается только SAFE. Поддержка BTC будет доступна в следующих версиях)',
    'YOU_SEND_FUNDS': 'Вы отправляете Ваши средства на Депозитный адрес.',
    'KEEP_WALLET_OPEN': 'Держите Ваш кошелёк открытым',
    'IMPORTANT_FUNDS': '[ВНИМАНИЕ] Средства обрабатываются лотами кратно 100 SAFE, 1000 SAFE, and 10000 SAFE.',
    'LARGE_LOT': 'Лоты большего размера обрабатываются раньше, чем меньшего.',
    'EG': 'Например, вы отправили 1393 SAFE на SAFE Deposit Address.<br>' +
          'Сперва будут обработаны 1000 SAFE<br>' +
          'затем 100 SAFE<br>' +
          'ещё 100 SAFE<br>' +
          'и ещё 100 SAFE',
    '93_SAFE': '93 SAFE останутся на Депозитном адресе.',
    'TO_CLEAR_THEM': 'Для обработки Вам необходимо прислать ещё 7 SAFE на Ваш SAFE Депозитный адрес.',
    'WHEN_IT_TOTALS': 'Когда наберётся сумма минимального лота 100 SAFE, запустится процесс на Вашем SAFE Jumblr Адресе.',
    'JADDR': 'Jumblr Адрес',
    'BTC_DEPOSIT': 'BTC Deposit',
    'SHOW_HIDE': 'Показать/Скрыть',
    'HIDDEN': 'Скрыто по соображениям безопасности.',
    'SAFE_DEPOSIT': 'SAFE Deposit',
    'JSTATUS': 'Jumblr Статус',
    'RESULT': 'Результат',
    'DEPOSITED': 'Deposited',
    'PUB_TO_PRIV': 'Публичный на Приватный',
    'PRIV_TO_PRIV': 'Приватный на Приватный',
    'PRIV_TO_PUB': 'Приватный на Публичный',
    'FINISHED': 'Завершено',
    'PENDING': 'В ожидании',
    'ERROR': 'Ошибка',
  },
  'DASHBOARD': {
    'SHOW_ALL_ADDR': 'Показать все адреса',
    'RPC_CONN_FAILURE': 'Не удалось установить соединение по RPC! Количество повторов',
    'REMOVE': 'Удалить',
    'STOP': 'Стоп',
    'SOFT_LOGOUT': 'Программный выход',
    'COMPLETE_LOGOUT': 'Полный выход',
    'GENERATE_SM': 'generate',
    'RECEIVE_ADDR_COPIED': 'адрес скопирован в буфер обмена',
    'SERVER_SM': 'сервер',
    'IS_UNREACHABLE': 'недоступен',
    'SERVER_SET_TO': 'server is set to',
    'SPV_AUTO_SWITCH': 'Попытка переключиться на другой сервер',
    'HOW_TO_SWITCH_MANUALLY': 'Как переключаться вручную',
    'SELECT_ADDRESS': '- Выбрать адрес -',
    'SEND_TOADDR_REQ': 'Требуется адрес получения.',
    'SEND_FROMADDR_REQ': 'Требуется адрес отправки.',
    'SEND_AMOUNT_REQ': 'Введите сумму для отправки.',
    'SEND_FEE_REQ': 'Убедитесь, что Вы учли комиссию.',
    'SEND_TOTAL_REQ': 'Убедитесь, что сумма и комиссия введены для подсчёта итогового значения.',
    'SEND_TX_PROGRESS': 'Транзакция в процессе. Детали транзакции будут отображены здесь после обработки.',
    'SUBTRACT_FEE': 'Вычесть комиссию из суммы отправки',
    'UNKNOWN': 'Unknown',
    'IN': 'IN',
    'OUT': 'OUT',
    'MINED': 'Mined',
    'IMMATURE': 'Immature',
    'ZADDR_NOT_LISTED': 'Z Адрес не отображаются кошельком',
    'ADDR_COPIED': 'Адрес скопирован',
    'QR_ERR_NO_VIDEO_DEVICE': 'Ошибка: устройств ввода видео не найдено!',
    'QR_ERR_UNKNOWN': 'Ошибка: неизвестная ошибка!',
    'SPV_CONN_ERROR': 'Ошибка подключения!',
    'SPV_CONN_ERROR_P1': 'Перейдите в «Настройки», выберите вкладку «Список серверов SPV», выберите новый сервер и нажмите «ОК».',
    'FAILED_TX_INFO': 'Сбой транзакции или процесс переиндексация продолжается. Неверные транзакции обычно отклоняются через некоторое время, в результате чего ваши средства возвращаются.',
    'SPV_CLAIMED_INTEREST': 'Начисленные проценты',
    'CLAIM_INTEREST_HELPER_BAR_P1': 'У Вас набежало',
    'CLAIM_INTEREST_HELPER_BAR_P2': 'к зачислению',
    'CLAIM_INTEREST_HELPER_BAR_P3': 'Зачислить',
    'CLAIM_INTEREST_HELPER_BAR_ALT_P1': 'У вас нет процентов к зачислению',
    'CLAIM_INTEREST_HELPER_BAR_ALT_P2': 'Проверить UTXO',
    'SEARCH': 'Поиск',
    'CURRENT_BLOCK_SM': 'текущий блок',
  },
  'TOASTR': {
    'INCORRECT_WIF': 'Не верный формат ключа (WIF)',
    'ERROR': 'Ошибка',
    'FAILED_TO_VERIFY_ADDR': 'Не удалось проверить адрес',
    'COIN_UNABLE_TO_STOP': 'Невозможно остановить @template@. Попробуйте снова.',
    'COIN_IS_STOPPED': 'остановлен',
    'COIN_IS_REMOVED': 'удалён',
    'JUMBLR_RESUMED': 'Jumblr продолжен',
    'JUMBLR_PAUSED': 'Jumblr приостановлен',
    'DATADIR_UNABLE_TO_CLEAR': 'Невозможно очистить',
    'DATADIR_CLEARED': 'каталог данных очищен',
    'PORT_IS_TAKEN': 'Порт @template@ уже занят!',
    'ERROR_STARTING_DAEMON': 'Ошибка запуска службы @template@.',
    'SAFECOIN_DATADIR_INVALID': 'Путь к каталогу Safecoin неверный.<br>Это должен быть абсолютный путь к существующей папке, которая не содержит пробелов и/или любых специальных символов.',
    'SAFECOIN_DATADIR_NOT_DIR': 'Путь к каталогу Safecoin не является каталогом.<br>Это должен быть абсолютный путь к существующей папке, которая не содержит пробелов и/или любых специальных символов.',
    'INVALID_ADDRESS': 'Не верный @template@ адрес',
    'RESTART_SAFEWALLET_WITH_REINDEX_PARAM': 'Перезапустите Safewallet и запустите Safecoin с параметром -reindex',
    'JUMBLR_DEPOSIT_ADDRESS_SET': 'Jumblr адрес пополнения установлен',
    'JUMBLR_SECRET_ADDRESSES_IMPORTED': 'Jumblr секретные адреса импортированы',
    'JUMBLR_SECRET_ADDRESS_IMPORTED': 'Jumblr секретный адрес импортирован',
    'JUMBLR_WRONG_PASSPHRASE': 'Предоставленная кодовая фраза имеет неправильный формат',
    'JUMBLR_SECRET_ADDRESS_SET': 'Jumblr секретный адрес установлен',
    'JUMBLR_SECRET_ADDRESSES_SET': 'Jumblr секретные адреса установлены',
    'ENTER_CORRECT_ADDR_COUNT': 'Введите правильное значение количества адресов',
    'TXID_COPIED': 'ID Транзакции скопирован',
    'CLAIM_INTEREST_BALANCE_SENT_P1': 'Ваш полный баланс отправлен на адрес',
    'CLAIM_INTEREST_BALANCE_SENT_P2': 'Проверьте свой новый баланс через несколько минут.',
    'SETTINGS_RESET': 'Настройки сброшены на значения по умолчанию',
    'SETTINGS_SAVED': 'Настройки сохранены',
    'TRANSACTION_FAILED': 'Не удалось выполнить транзакцию',
    'WALLET_NOTIFICATION': 'Wallet Notification',
    'ACCOUNT_NOTIFICATION': 'Account Notification',
    'COIN_NOTIFICATION': 'Coin Notification',
    'TX_NOTIFICATION': 'Transaction Notification',
    'SERVICE_NOTIFICATION': 'Service Notification',
    'LOGIN_NOTIFICATION': 'Login Notification',
    'SETTINGS_NOTIFICATION': 'Settings Notification',
    'RECADDR_UPDATED': 'Список адресов получения обновлен',
    'SWITCHED_TO': 'переключен в',
    'MODE': 'Режим',
    'TX_SENT': 'Транзакция отправлена',
    'TX_SEND_ERR': 'Не удалось выполнить транзакцию',
    'LOOKS_LIKE': 'Похоже',
    'ALREADY_RUNNING': 'уже запущен',
    'STARTED_IN': 'Запущен ',
    'SAFECOIN_ERR': 'Невозможно запустить Safecoind',
    'SIGNED_TX_GENERATED': 'Подписанная транзакция сгенерирована',
    'SIGNED_TX_GENERATED_FAIL': 'Генерация подписанной транзакции не удалась',
    'SENDING_TX': 'Отправляем транзакцию в сеть',
    'SIGNED_TX_SENT': 'Подписанная транзакция успешно отправлена',
    'GETTING_TXID_INFO': 'Получение txid для обновления данных средств',
    'REFRESHING_FUNDS': 'Обновление средств кошелька',
    'TX_FAILED': 'Исходящая транзакция не удалась. Пожалуйста, проверьте страницу отправки для деталей.',
    'TX_SENT_ALT': 'Транзакция успешно отправлена. Проверьте страницу отправки для деталей.',
    'COIN_STARTED': 'монета запущена',
    'ADDR_ALREADY_REG': 'адрес уже зарегистрирован в сети.',
    'REG': 'Зарегистрирован',
    'REG_ADDR': 'адрес в сети.',
    'REG_ADDR_FAILED': ' регистрация не удалась. Пожалуйста, повторите.',
    'INVALID_QUERY': 'Неверный запрос',
    'TRY_AGAIN': 'Пожалуйста, повторите.',
    'ADDR_ISNT_REG': 'Адрес не зарегистрирован в сети. Пожалуйста, зарегистрируйтесь',
    'INVALID_QUERY_ALT': 'Неверный запрос. Пожалуйста, повторите.',
    'VALIDATION_SUCCESS': 'Успешная проверка в сети',
    'SAFE_NATIVE_CON_ERROR': 'Ошибка подключения. Внешний кошелек запущен?',
    'LOGIN_SUCCESSFULL': 'Авторизация удалась',
    'OPPS': 'Опаньки... Что-то пошло не так!',
    'INVALID_PASSPHRASE': 'Неверная кодовая фраза. Убедитесь, что ваша кодовая фраза верна или создайте новый кошелек.',
    'WALLET_CREATED_SUCCESFULLY': 'Кошелек успешно создан',
    'LOGOUT_SUCCESSFULL': 'Выход удался',
    'WALLET_LOCKED': 'Кошелёк успешно заблокирован',
    'PRIV_KEY_IMPORTED': 'Приватный Ключ успешно импортирован!',
    'PRIV_KEY_NOT_IMPORTED': 'Приватный Ключ не импортирован.',
    'ADDED_TO': 'добавлено в',
    'SUCCESSFULLY': 'Успешно',
    'COIN_SELECTION': 'Выбор монеты',
    'SELECTION_NOT_FOUND': 'Local coin list is not found',
    'AWAITING_TX_RESP': 'Awaiting transaction data response',
  },
  'COIN_WALLETS': {
    'TX_FAILED': 'Транзакция не удалась',
    'TX_SUCCESS': 'Успешная транзакция',
    'TX': 'Транзакция',
  },
  'IAPI': {
    'PUBLIC_SM': 'public',
    'CON_STATUS': 'Статус подключения',
  },
  'SAFE_NATIVE': {
    'SELECT_ADDRESS': 'Выберите Публичный или Приватный адрес',
    'SELECT_ADDRESS_ALT': 'Выберите Публичный или Приватный адрес SAFE',
    'PRIVATE': 'приватный',
    'NEW_ADDR_GENERATED': 'Новый адрес успешно сгенерирован',
    'QUEUED': 'В очереди',
    'PLEASE_REFRESH': 'Нажмите кнопку обновить примерно через минуту, чтобы увидеть обновленный статус',
    'EXECUTING': 'Выполняется',
    'FAILED': 'Не удалось',
    'SUCCESS': 'Успешно',
    'MESSAGE': 'Сообщение',
    'EXECUTION_SECONDS': 'Время выполнения',
    'WAIT_UNTIL_SYNCED': 'История транзакций недоступна во время синхронизации',
    'TXID': 'ID Транзакции',
    'ZCASH_PARAMS_MISSING': 'Zcash params отсутствуют или неполны:',
    'ZCASH_PARAMS_MISSING_ROOT_DIR': '- отсутствует корневая папка',
    'ZCASH_PARAMS_MISSING_PROVING_KEY': '- отсутствует ключ подтверждения',
    'ZCASH_PARAMS_MISSING_VERIFYING_KEY': '- отсутствует ключ проверки',
    'ZCASH_PARAMS_MISSING_PROVING_KEY_SIZE': '- размер ключа подтверждения некорректный',
    'ZCASH_PARAMS_MISSING_VERIFYING_KEY_SIZE': '- размер ключа проверки некорректный',
  },
  'LOGIN': {
    'OR_USE_A_SHORTCUT': 'или использовать ярлык',
    'PIN_LOGIN_INFO': 'Вы можете войти введя кодовую фразу или PIN',
    'QUICK_ACCESS': 'Быстрый доступ',
    'PWD_REQ': 'Требуется пароль.',
    'WALLET_SEED_REQ': 'Требуется кодовая фраза.',
    'SAVED_WALLET_SEED': 'Вы сохранили Вашу кодовую фразу от кошелька?',
    'SEED_MAKE_SURE_BACKUP': 'Убедитесь, что у Вы сохранили кодовую фразу. Без неё вы не сможете получить доступ к своему кошельку в будущем!',
    'YES_I_BACKUP': 'Да, я уверен в том, что сделал резервную копию.',
    'WALLET_LOCKED_LOGIN': 'Кошелёк заблокирован. Пожалуйста, войдите.',
    'CANCEL': 'Отмена',
    'UNLOCK': 'Разблокировать',
    'SIGN_IN': 'Вход',
    'WELCOME': 'Приветствуем!',
    'ENTER_VALUE_AGAIN': 'Пожалуйста, введите то же значение снова',
    'CUSTOM_WALLET_SEED': 'Custom wallet seed',
    'MUST_ENTER_SEED': 'Вы должны ввести кодовую фразу',
    'INVALID_SEED': 'Неправильная кодовая фраза',
    'SEED_NOT_OF_TYPE': 'The inserted seed is not of type',
    'IGUANA_SEED': 'Iguana (256 bits)',
    'WAVES_SEED': 'Waves',
    'NXT_SEED': 'NXT',
    'SEED_COPIED': 'Кодовая фраза скопирована',
    'SEED_SUCCESSFULLY_COPIED': 'Кодовая фраза успешно скопирована',
    'ENCRYPT_SEED': 'Зашифровать входную кодовую фразу',
    'PUBKEY': 'публичный ключ',
    'ENCRYPT_KEY': 'Зашифровать ключ',
    'DECRYPT_KEY': 'Расшифровать ключ'
  },
  'SIDEBAR': {
    'EDEX_MOTTO': 'Наиболее безопасный, простой и нативный децентрализованный обмен',
    'JUMBLR_MOTTO': 'Безопасный, нативный и децентрализованный анонимайзер монеты',
  },
  'SETTINGS': {
    'DAEMON_PORTS': 'Порты сервиса',
    'KEY_IS_NOT_FOUND': 'Ключ не найден',
    'ADDRESSES_SM': 'адреса',
    'ACCOUNT_SM': 'аккаунт',
    'ACCOUNTS_SM': 'аккаунты',
    'GET_KEY': 'Получить ключ',
    'DATADIR_DELETE_PROMPT': 'Вы уверены, что хотите очистить каталог с данными @template@?',
    'YES': 'Да',
    'NO': 'Нет',
    'KEEP': 'Сохранить',
    'DELETE': 'Удалить',
    'COIND_DELETING': 'Удаляем @template@ данные..',
    'COIND_DATADIR_CLEAR_P1': 'Предупреждение: следующая форма уничтожит все данные о нативном клиенте монеты!',
    'COIND_DATADIR_CLEAR_P2': 'Ничего не трогайте, если вы не знаете, что делаете.',
    'GET_KEYS': 'Получить ключи',
    'FETCHING_KEYS': 'Получение ключей',
    'SEARCH_KEY_PATTERN': 'Искать паттерн ключа',
    'ADDRESS': 'Адрес',
    'KEYS_SM': 'ключи',
    'FOUND': 'Found',
    'PICK_A_COIN': 'Укажите монету',
    'CLEAR_NATIVE_DATADIR': 'Очистить папку нативного клиента монеты',
    //'KEYS_SM': 'ключи',
    'KEYS_CAP': 'Ключи',
    'BIP39_DISC': 'Аппаратные кошельки отказ от ответственности: используя эту форму, вы признаёте риски разоблачения вашей кодовой фразы',
    'BIP39_DESC_P1': 'Описание: Форма ниже позволяет искать публичный ключ на основе диапазона выбранных комбинаций (число аккаунтов * глубина пути адреса аккаунта).',
    'BIP39_DESC_P2': 'Приложение может "зависнуть" на несколько секунд во время процедуры поиска.',
    'SHOW_APP_RUNTIME_LOG': 'Показать журнал (log) приложения',
    'WRONG_PASSPHRASE': 'Ошибочная кодовая фраза!',
    'SPV_SERVER_LIST_DESC': 'Выбор списка серверов доступен только для активных монет, у которых есть более одного активного подключения.',
    'SPV_SERVERS': 'список серверов SPV',
    'SPV_SINGLE_SERVER_NOTICE': 'Только один сервер electrum доступен. SPV проверка приходит от того же сервера, что и рассылает данные.',
    'SAFE_MAIN_SYNC_ONLY': 'SAFE main sync only',
    'RPC_FETCH_ONLY_DESC': 'Получать только данные синхронизации. Пропустить любые другие запросы, которые могут ухудшить скорость синхронизации.',
    'RESET_TO_DEFAULT': 'Восстановить значения по умолчанию',
    'PROGRESS': 'Выполнение',
    'SUPPORT': 'Поддержка',
    'SUPPORT_TICKETS': 'Заявки службы поддержки',
    'GET_SLACK_INVITE': 'Получить приглашение',
    'ADDRESS_LIST': 'Адрес',
    'WIF_KEY_LIST': 'ключ (WIF)',
    'CLI_RESPONSE': 'ответ CLI',
    'PASSPHRASE_REQ': 'Требуется кодовая фраза.',
    'SAVE_APP_CONFIG': 'Сохранить конфигурацию приложения',
    'CONFIG_RESTART_REQUIRED': 'Любые изменения в конфигурации приложения требуют перезапуска приложения!',
    'APP_CONFIG': 'Настройка приложения',
    'APP_INFO': 'Информация приложения',
    'APP_RELEASE': 'Релиз приложения',
    'NAME': 'Имя',
    'VERSION': 'Версия',
    'SYS_INFO': 'Системная информация',
    'ARCH': 'Архитектура',
    'OS_TYPE': 'Тип ОС',
    'OS_PLATFORM': 'Платформа ОС',
    'OS_RELEASE': 'Релиз ОС',
    'CPU': 'CPU',
    'CPU_CORES': 'Ядра CPU',
    'MEM': 'Память',
    'LOCATIONS': 'Расположение',
    'CACHE': 'Cache',
    'CONFIG': 'Config',
    'BIN': 'Bin',
    'DIR': 'Dir',
    'ADD_PEER_IP': 'Добавить IP пира',
    'APP_SESSION': 'Сессия приложений',
    'EXPORT_KEYS_NOTE': 'Примечание: важно, чтобы вы предоставили ту же кодовую фразу, которую вы использовали для входа в кошелек!',
  },
  'TX_INFO': {
    'ADDRESS': 'адрес',
    'AMOUNT': 'количество',
    'CATEGORY': 'категория',
    'CONFIRMATIONS': 'подтверждения',
  },
  'ZCPARAMS_FETCH': {
    'DOWNLOADING_ZCASH_KEYS': 'Загружаем ключи Zcash',
    'BOTH_KEYS_VERIFIED': 'Ключи Zcash загружены и проверены!',
    'PLEASE_RESTART': 'Пожалуйста, перезапустите приложение.',
    'ZCPARAMS_VERIFICATION_ERROR_P1': 'Zcash param',
    'ZCPARAMS_VERIFICATION_ERROR_P2': 'ошибка проверки!',
    'ZCPARAMS_FETCH': 'Получение ZCash Params',
    'SELECT_ZCPARAMS_SOURCE': 'Выберите источник загрузки ключей Zcash',
    'DOWNLOAD': 'Загрузить',
  },
  'SEND': {
    'SELF': 'Self',
    'ALL': 'All',
    'BAD_TXN_SPENT_ERR1': 'This particular error can happen in the following cases:',
    'BAD_TXN_SPENT_ERR2': 'Your machine\'s clock is not set properly',
    'BAD_TXN_SPENT_ERR3': 'SPV server is temporary out of sync. Try to switch over to another one.',
    'BAD_TXN_SPENT_ERR4': 'Double spend in case you just made another transaction',
    'MIN_AMOUNT_IS': 'min @template@ amount is',
    'AMOUNT_IS_TOO_SMALL': 'Amount @template@ is too small',
    'MAX_AVAIL_BALANCE': 'max available balance is',
    'TXID_COPIED': 'TXID copied to clipboard',
    'RESULT': 'Результат',
    'PROCESSING_TX': 'Транзакция в процессе',
    'TRANSACTION_ID': 'ID транзакции',
    'SUCCESS_SM': 'успешно',
    'WARNING': 'Предупреждение',
    'WARNING_SPV_P1': 'данные вашего кошелька проверены только одним сервером!',
    'WARNING_SPV_P2': 'Если вы все еще хотите продолжить, нажмите «Подтвердить».',
    'SPV_VERIFYING': 'Проверка данных транзакции',
    'PROCESSING_REQ': 'Обработка запросов',
    'LOCKED_PLEASE_WAIT': 'Заблокировано, пожалуйста, подождите',
    'UPDATE': 'Обновить',
    'SELECT_T_OR_Z_ADDR': 'Выберите Публичный или Приватный (z) адрес',
    'ENTER_T_OR_Z_ADDR': 'Введите публичный или приватный адрес',
    'ENTER_ADDRESS': 'Введите адрес',
    'AWAITING': 'Ждёт очереди',
    'PROCESSING': 'Обработка',
    'ERROR_CODE': 'Ошибка код',
    'WAITING': 'Waiting',
    'PROCESSING_TRANSACTION': 'Обрабатываем транзакцию',
    'NOTE_IT_WILL_TAKE': 'Внимание: для завершения транзакции может потребоваться несколько минут',
    'ENTER_AN_ADDRESS': 'Введите адрес',
    'YOU_PICKED_OPT': 'Вы выбрали опцию',
    'PLEASE_WAIT': 'Пожалуйста подождите',
    'SEND_TO_ADDRESS_MIN_LENGTH': 'Адрес отправки должен быть минимум 34 символа',
    'AMOUNT_POSITIVE_NUMBER': 'Количество должно быть больше нуля',
    'FEE_POSITIVE_NUMBER': 'Комиссия должна быть больше нуля',
    'TOTAL_AMOUNT_POSITIVE_NUMBER': 'Итого (количество-комиссия) должно быть больше нуля',
    'INSUFFICIENT_FUNDS': 'Для совершения этой транзакции у Вас недостаточно средств',
    'SELECT_SOURCE_ADDRESS': 'Укажите адрес источник ( От )',
    'QR_COIN_MISMATCH_MESSAGE_IMPORT_COIN': 'У QR-кода были монеты ',
    'QR_COIN_MISMATCH_MESSAGE_ACTIVE_COIN': '. У Вас ',
    'QR_COIN_MISMATCH_MESSAGE_END': ' Пожалуйста, убедитесь что у Вас активна та же самая монета, какую Вы хотите импортировать!',
    'QR_COIN_MISMATCH_TITLE': 'Монеты не совпадают',
    'SEND_NATIVE_SYNC_WARNING': 'Ваш кошелёк не полностью синхронизирован! Пожалуйста, дождитесь 100% загрузки.',
  },
  'FIAT_CURRENCIES': {
    'AUD': 'Australian Dollar (AUD)',
    'BRL': 'Brazilian Real (BRL)',
    'GBP': 'British Pound (GBP)',
    'BGN': 'Bulgarian Lev (BGN)',
    'CAD': 'Canadian Dollar (CAD)',
    'HRK': 'Croatian Kuna (HRK)',
    'CZK': 'Czech Koruna (CZK)',
    'CNY': 'Chinese Yuan (CNY)',
    'DKK': 'Danish Krone (DKK)',
    'EUR': 'Euro (EUR)',
    'HKD': 'Hong Kong Dollar (HKD)',
    'HUF': 'Hungarian Forint (HUF)',
    'INR': 'Indian Rupee (INR)',
    'IDR': 'Indonesian Rupiah (IDR)',
    'ILS': 'Israeli Shekel (ILS)',
    'JPY': 'Japanese Yen (JPY)',
    'KRW': 'Korean Won (KRW)',
    'MYR': 'Malaysian Ringgit (MYR)',
    'MXN': 'Mexican peso (MXN)',
    'NZD': 'New Zealand Dollar (NZD)',
    'NOK': 'Norwegian Krone (NOK)',
    'PHP': 'Philippine Peso (PHP)',
    'PLN': 'Polish Zloty (PLN)',
    'RON': 'Romanian Leu (RON)',
    'RUB': 'Russian Ruble (RUB)',
    'SGD': 'Singapore Dollar (SGD)',
    'ZAR': 'South African Rand (ZAR)',
    'SEK': 'Swedish Krona (SEK)',
    'CHF': 'Swiss Franc (CHF)',
    'THB': 'Thai Baht (THB)',
    'TRY': 'Turkish Lira (TRY)',
    'USD': 'US Dollar (USD)',
  },
  'ASSETCHAINS': {
    'SAFE': 'SafeCoin (SAFE)',
    'BTCZ': 'BitcoinZ (BTCZ)',
    'ANON': 'ANON (ANON)',
    'ZCL': 'ZClassic (ZCL)',
    'XSG': 'SnowGem (XSG)',
  },
  'DEX': {
    'GEN_NEW_PASSPHRASE': 'Генерировать новую кодовую фразу',
    'LOGIN': 'Войти',
    'BACKUP_PASSPHRASE_P1': 'Сохраните  вашу кодовую фразу',
    'BACKUP_PASSPHRASE_P2': 'она не может быть восстановлена!',
    'ESTIMATED_BALANCE': 'Предполагаемый баланс',
    'TRADE_HISTORY_SM': 'история операций',
    'ELECTRUM_MODE': 'Electrum режим',
    'NATIVE_MODE': 'Нативный режим',
  },
};
