export const LANG_UA = {
  'WALLETS_INFO': {
    'ADDRESS': 'IP Адреса',
    'ADDRESS_LOCAL': 'Локальна IP Адреса',
    'SERVICES': 'Сервіси',
    'VERSION': 'Версія',
    'SUBVERSION': 'Субверсія',
    'WHITELISTED': 'Білий список',
    'INBOUND': 'Вхідний',
    'TIME_OFFSET': 'Часовий зсув',
    'PING_TIME': 'Тривалість пінгу',
    'CONNECTION_TIME': 'Тривалість підключення',
    'LAST_SEND': 'Остання відправка',
    'LAST_RECEIVED': 'Останнє отримання',
    'DATA_SENT': 'Дані відправлені',
    'DATA_RECEIVED': 'Дані отримані',
    'BAN_SCORE': 'Штрафні бали',
    'STARTING_HEIGHT': 'Початкова висота',
    'SYNCED_HEADERS': 'Синхронізовано заголовків',
    'SYNCED_BLOCKS': 'Синхронізовано блоків',
    'NETWORK_TOTALS': 'Підсумок мережі',
    'TIME': 'Час',
    'PEERS': 'Піри',
    'LOADING': 'Завантаження...',
  },
  'IMPORT_KEY': {
    'IMPORT': 'Імпортувати',
    'IMPORT_KEY': 'Імпортувати ключ',
    'TWO_FORMS_BELOW_P1': 'Дві форми нижче дозволяють Вам імпортувати',
    'TWO_FORMS_BELOW_P2': 'парольну фразу (seed) або',
    'TWO_FORMS_BELOW_P3': 'ключ',
    'PASSPHRASE': 'Парольна фраза / seed',
    'NOTICE': 'Повідомлення',
    'NOTICE_DESC': 'імпорт парольної фрази призведе до повного сканування блокчейна',
    'SAFE_RESCAN_WARNING_TIME': 'Процес сканування блокчейна може зайняти багато часу',
    'SHOW_ADDRESS_AND_WIF': 'Показати адресу та ключ (WIF)',
    'ADDRESS': 'Адреса',
    'OR': 'або',
    'TRIGGER_RESCAN': 'Сканування',
    'RESCAN_TIP': 'Використовуйте цю опцію, якщо хочете зробити повне сканування після імпорту ключа. Якщо у Вас кілька адрес зробіть почергове імпортування і включіть цю опцію при імпорті останнього.',
    'WIF_KEY': 'ключ (WIF)',
    'IMPORT_AND_RESCAN': 'Імпорт та рескан',
  },
/*  'CLAIM_INTEREST': {
    'SHOW_ZERO_INTEREST': 'Показывать нулевые проценты',
    'REQ_P1': 'Требования к начислению процентов',
    'REQ_P2': 'отправка средств была произведена минимум 1 час назад поле locktime установлено, и начисление больше, чем',
    'CLAIM_INTEREST': 'Зачислить @template@ проценты',
    'LOADING': 'Загружаем данные процентов',
    'NO_DATA': 'Нет данных',
    'TIP': 'Tip',
    'NOTICE': 'Повідомлення',
    'TIP_DESC': 'не пытайтесь зачислить процент меньше 0.01 SAFE. Стоимость транзакции может оказаться больше або равна сумме процентов.',
    'NATIVE_INTEREST_CHANGE_DESC': 'Вероятно, что проценты будут зачислены как отдельная транзакция на новый SAFE-адрес.',
  },*/
  'ABOUT': {
    'SAFEWALLET_WALLET': 'Гаманець Safewallet',
    'ABOUT_SAFEWALLET': 'Про Safewallet',
    'SAFEWALLET_MODES': 'Гаманець Safewallet - програма, що дозволяє Вам керувати кількома гаманцями криптовалют. ' +
                     'Ви можете налаштувати гаманець для роботи в декількох режимах:',
    'NATIVE_MODE_DESC': 'Доступно для декількох криптовалют, аналогічно \'Full Mode\' але володіє розширеною функціональністю.',
    'SAFEWALLET_CAPABILITIES': 'Safewallet включає в себе наступні можливості:',
    'BARTER_DEX_DESC': 'Простий обмін криптовалют через shapeshift-подібний сервіс.',
    'SAFEWALLET_NOTE': 'Пояснення: Safewallet Гаманець все ще в розробці. ' +
                    'Він безпечний у використанні, але Ви повинні робити резервні копії. ' +
                    'Ми не рекомендуємо Вам використовувати його в якості основного гаманця криптовалют.',
    'TESTERS': 'Тестування',
    'TESTERS_P1': 'Ви можете допомогти нам зробити Safewallet кращим. ',
    'TESTERS_P2': 'Скачайте і встановіть останній реліз,',
    'TESTERS_P3': 'повідомляйте про будь-які помилки знайдених в програмі команді розробників.',
    'TESTERS_P4': 'Ваша допомога незамінна!',
    'SAFEWALLET_DAPPS': 'Safewallet також підтримує такі програми:',
    'JUMBLR_DESC': 'Децентралізований Bitcoin Tumbler, для забезпечення конфіденційності і зниження комісії.',
    'BARTER_DEX_DESC_ALT': 'Децентралізований обмінник криптовалют.',
    'CHANNEL': 'Відмінити',
    'GET_AN_INVITE': 'Отримайте запрошення',
    'GET_AN_INVITE_P2': 'в наш чат, якщо Ви ще не зареєстровані там'
  },
  'API': {
    'DAEMON_IS_STILL_RUNNING': 'сервіс гаманця все ще працює. Якщо ви хочете повністю зупинити його - наступного разу, використовуйте значок зупинки.',
    'CONN_ERROR': 'Помилка підключення',
    'SAFE_PASSIVE_ERROR': 'Будь ласка, переконайтеся, що safecoind запущений',
    'ERROR_SM': 'помилка',
    'ADDRESS_ALREADY_REG': 'Адреса вже зареєстрована',
    'COULDNT_COPY_ADDRESS': 'Не можу скопіювати адресу в буфер',
    'COULDNT_CREATE_SEED': 'Не можу створити нову (парольну фразу) seed',
    'WALLETDAT_MISMATCH': 'Ваш файл wallet.dat не відповідає блокчейну. Будь ласка, перезапустіть гаманець з параметром -reindex.',
    'PEER_ADDED': 'Пір доданий',
    'ADDNODE_ALREADY_PENDING': 'Підключення до ноді вже очікується',
    'PEER_ALREADY_CONN': 'Пір вже підключений ',
    'ADDNODE_NEEDS_COIN': 'для Addnode, демон монети повинен бути активний',
    'PRIVKEY_IN_WALLET': 'Приватний ключ вже доданий',
    'ILLEGAL_PRIVKEY': 'Помилковий приватний ключ',
    'NO_ACTIVE_COIN': 'Немає активних монет',
  },
  'INDEX': {
    'WALLET_OFFLINE': 'Safewallet не може підключитися до Інтернету.',
    'OFFLINE': 'Офлайн',
    'TOGGLE_COIN_CONTEXT_MENU': 'Переключити контекстне меню монети',
    'TOP_MENU': 'Головне меню',
    'ERROR_READING': 'Помилка читання',
    'SHOW': 'Показати',
    'SPV_SERVER_IP': 'IP Сервера',
    'SPV_SERVER_PORT': 'Порт Сервера',
    'SPV_SERVER_CON_TYPE': 'Тип підключення',
    'COIND_DOWN_MODAL_ERROR': ' debug.log порожній, схоже, що демон не зміг коректно запуститися. Спробуйте повторити.',
    'SPV_MODE': 'Lite (SPV) Режим',
    'PROGRESS_RESCANNING_BLOCKS': '(Сканування блоків)',
    'BLOCKS': 'Блок',
    'PLEASE_WAIT_UNTIL_RESCAN_FINISHED': 'Будь ласка, дочекайтеся закінчення процесу сканування блоків',
    'VERIFYING_BLOCKS': 'Перевірка блоків',
    'ALL': 'Всі',
    'NATIVE_ONLY_MODE': 'Нативний режим',
    'NORMAL_MODE': 'Звичайний режим ',
    'T_FUNDS': 'Публічні кошти',
    'HASH': 'Хеш',
    'SYNC_IN_PROGRESS': 'Синхронізація в процесі.',
    'UI_UPDATE_DOWNLOADED': 'UI оновлення завантажено. Перевіряється',
    'UI_UPDATED': 'UI був оновлений!',
    'UI_UPDATE_ERROR': 'Помилка під час перевірки файлу поновлення! Спробуйте ще раз.',
    'CHECKING_UI_UPDATE': 'Перевіряю наявність оновлень UI',
    'NEW_UI_UPDATE': 'Вийшла нова версія UI',
    'YOU_HAVE_LATEST_UI': 'У Вас встановлена остання версія UI',
    'DOWNLOADING_UI_UPDATE': 'Завантажую UI оновлення',
    'LAST_50_LINES': 'останні 50 рядків',
    'IS_DOWN': 'недоступний',
    'REINDEX': 'переіндексація',
    'RESCAN': 'сканування',
    'BACKGROUND_PROCESS': 'фоновий процес',
    'NONE': 'none',
    'DAEMON_PARAM': 'Параметри служби',
    'FILTER_BY_ADDRESS': 'Сортувати за адресою',
    'RESCANNING_LAST_BLOCKS': 'Скануємо останні блоки...',
    'NO_DATA_AVAILABLE': 'Дані недоступні',
    'LOADING': 'Завантажується',
    'ACTIVATING_SM': 'активація',
    'DL_BLOCKS': 'завантаження блоків',
    'RESCAN_SM': 'сканування блоків',
    'REINDEX': 'переіндексація блоків на диску',
    'BLOCKS_SM': 'блок',
    'LOADING_BLOCKS': 'Завантаження даних, зачекайте...',
    'WEAK_SEED': 'Слабка парольна фраза!',
    'YOUR_SEED_MUST_CONTAIN': 'Ваша парольна фраза повинна відповідати наступним вимогам:',
    'YOUR_SEED_MUST_CONTAIN1': '- як мінімум 1 велика літера',
    'YOUR_SEED_MUST_CONTAIN2': '- як мінімум 1 цифра',
    'YOUR_SEED_MUST_CONTAIN3': '- як мінімум 1 спеціальний символ ',
    'YOUR_SEED_MUST_CONTAIN4': '- мінімум 10 символів',
    'YOUR_SEED_MUST_CONTAIN5': '- максимум 100 символів',
    'EXECUTE': 'Виконати',
    'TYPE_CLI_CMD': 'Введіть CLI-сумісну команду',
    'COIN': 'Монета',
    'UPDATE': 'Оновлення',
    'UI_UPDATE': 'UI оновлення',
    'CHECK_FOR_UPDATE': 'Перевірити оновлення',
    'UPDATE_UI_NOW': 'Оновити UI зараз',
    'BINS_UPDATE': 'Оновлення виконуючих файлів',
    'UPDATE_BINS_NOW': 'Оновити виконуючі файли',
    'CLI_SELECT_A_COIN': 'Виберіть монету і введіть CLI-сумісну команду',
    'CLI_NATIVE_COIN': 'Виберіть монету',
    'IMPORT': 'Імпортувати',
    'CHECK': 'Перевірити',
    'VALIDATE': 'Валідація',
    'COPY_TO_CLIPBOARD': 'Скопіювати в буфер',
    'EMPTY_DEBUG_LOG': 'debug.log порожній',
    'RESTART': 'Перезапуск',
    'WALLET_INFO': 'Інформація про гаманець',
    'ADD_COIN': 'Додати монету',
    'STOP': 'Зупинити',
    'START': 'Старт',
    'ACTIVE_ADDRESS': 'активна адреса',
    'NO_DATA': 'Історія недоступна',
    'LOADING_HISTORY': 'Завантажуємо історію транзакцій',
    'CLOSE': 'Зарити',
    'SHOW': 'Показати',
    'SHOWING': 'Показано',
    'OF': 'від',
    'TO_ALT': 'до',
    'SEARCH': 'Пошук',
    'PREVIOUS': 'Попередній',
    'NEXT': 'Наступний',
    'ENTRIES_SM': 'записів',
    'SYNC_ERR_BLOCKS': 'Підключаємося до пірів...',
    'SELECT_A_COIN': 'Виберіть монету для додавання в Safewallet',
    'WALLETS': 'Гаманці',
    'ACTIVATE_COIN': 'Активувати монету',
    'WELCOME_PLEASE_ADD': 'Ласкаво просимо.',
    'WELCOME_PLEASE_ADD2': 'Будь ласка, додайте монету для старту.',
    'SELECT_SEED_TYPE': 'Будь ласка, виберіть сумісний тип парольної фрази гаманця',
    'SELECT': '-Обрати-',
    'NATIVE_MODE': 'Native режим',
    'NATIVE_MODE_DESC1': 'Цей режим доступний тільки для: SafeCoin. ' +
                         'Цей режим',
    'NATIVE_MODE_DESC2': 'завантажує повний блокчейн.',
    'NATIVE_MODE_DESC3': 'тільки цей режим дозволяє Вам робити',
    'NATIVE_MODE_DESC4': 'Z Транзакції',
    'NATIVE_MODE_DESC5': 'Приватні Транзакції',
    'CLOSE': 'Закрити',
    'PLEASE_USE': 'Будь-ласка, використовуйте їх',
    'OR': 'або',
    'TO_USE': 'використати',
    'WELCOME_LOGIN': 'Ласкаво просимо.',
    'WELCOME_LOGIN2': 'Будь ласка, авторизуйтесь',
    'WALLET_SEED': 'Парольна фраза / ключ (WIF)',
    'SIGN_IN': 'Увійти',
    'CREATE_WALLET': 'Створити новий гаманець',
    'LOGIN_ANOTHER_WALLET': 'Увійти в інший гаманець',
    'CONFIRM_SEED': 'Підтвердіть парольний фразу',
    'REGISTER': 'Реєстрація',
    'BACK_TO_LOGIN': 'Повернутися до Входу',
    'TOGGLE_NAV': 'Переключити навігацію',
    'TOGGLE_SEARCH': 'Переключити пошук',
    'TOGGLE_MENUBAR': 'Перемикати панель меню',
    'SETTINGS': 'Налаштування',
    'LOGOUT': 'Завершити сеанс',
    'DASHBOARD': 'Головна панель',
    'WALLET_SETTINGS': 'Налаштування гаманця',
    'SAFE_WALLET': 'Гаманець Safecoin',
    'ZC_WALLET': 'Гаманець Zcash',
    'ACTIVE_COINS': 'Активувати Монети',
    'TRANSACTIONS': 'Транзакції',
    'SEND': 'Відправити',
    'RECEIVE': 'Отримати',
    'BUNDLES': 'Групи',
    'BALANCES': 'Баланси',
    'BALANCE': 'Баланс',
    'VALIDATED': 'Підтверджено',
    'NO_WALLET_CAPS': 'ГАМАНЕЦЬ НЕ ВИБРАНИЙ',
    'PLEASE_SELECT_A_WALLET': 'Будь ласка, виберіть гаманець зі списку активних монет зліва.',
    'ADDRESS': 'Адреса',
    'MY': 'Моя',
    'COPY': 'копіювати',
    'INTEREST_EARNED': 'Нараховані відсотки',
    'TOTAL_BALANCE': 'Загальний Баланс',
    'GET_BALANCE': 'Дізнатися баланс',
    'REFRESH': 'Оновити',
    'LIST_UNSPENT': 'Списк не витрачених',
    'LIST_TRANSACTIONS': 'Список транзакцій',
    'TRANSACTION_HISTORY': 'Історія транзакцій',
    'DIRECTION': 'Напрямок',
    'CONFIRMATIONS': 'Підтвердження',
    'AMOUNT': 'Кількість',
    'TIME': 'Час',
    'DEST_ADDRESS': 'Адреса отримувача',
    'TX_DETAIL': 'Подробиці Tx',
    'FILL_SEND_FORM': 'Заповніть форму відправки',
    'FILL_SEND_DETAILS': 'Вкажіть деталі переказу',
    'CONFIRMING': 'Підтвердження',
    'CONFIRM_DETAILS': 'Переконайтеся в правильності даних',
    'PROCESSING_TX': 'Обробляємо Tx',
    'PROCESSING_DETAILS': 'Обробка та відображення деталей',
    'SEND_FROM': 'Надсилаємо З',
    'SEND_TO': 'Надсилаємо На',
    'FEE': 'Комісія',
    'TOTAL': 'Загалом',
    'AMOUNT_SM': 'кіль-ть',
    'DONT_SEND': 'Не відправляти транзакцію - показати мені підписаний текст транзакції.',
    'TO': 'Кому:',
    'TX_FEE_REQ': 'Комісія транзакції (потрібно майнерам)',
    'FROM': 'Від кого:',
    'CONFIRM': 'Підтвердити',
    'BACK': 'Назад',
    'TRANSACTION_RESULT': 'Результат транзакції',
    'KEY': 'Ключ',
    'VALUE': 'Значення',
    'INFO': 'Інформація',
    'MAKE_ANOTHER_TX': 'Зробити іншу транзакцію',
    'RECEIVING_ADDRESS': 'Адреси отримання',
    'TYPE': 'Тип',
    'INTEREST': 'Проценти',
    'ACTIVATING_CHAIN': 'Активація кращого ланцюга блоків',
    'SAFE_STARTED': 'Служба Safecoind була запущена.<br>' +
                    'Будь ласка, зачекайте, поки найкращий ланцюг буде активований.<br>' +
                    'Підказка: у разі, якщо синхронізація зависла - перезапустіть гаманець.',
    'CONNECTIONS': 'Підключення',
    'TRANSPARENT_BALANCE': 'Публічний баланс',
    'Z_BALANCE': 'Приватний (Z) баланс',
    'INTEREST_EARNED': 'Нараховані Відсотки',
    'ZT_BALANCE': 'Загальний (Z+T) Баланс',
    'GET_NEW_ADDRESS': 'Створити нову адресу',
    'TRANSPARENT_ADDRESS': 'Публічний адреса',
    'PRIVATE_Z_ADDRESS': 'Приватна адреса',
    'OPERATIONS_STATUSES': 'Стан операцій',
    'STATUS': 'Статус',
    'RESULT': 'Результат',
    'WALLET_INFO': 'Інформація про гаманець',
    'WALLET_VERSION': 'Версія гаманця',
    'UNCONFIRMED_BALANCE': 'Непідтверджений баланс',
    'IMMATURE_BALANCE': 'Незрілий баланс',
    'TOTAL_TX_COUNT': 'Загальна кількість транзакцій',
    'INFO': 'Інформація',
    'VERSION': 'Версія',
    'PROTOCOL_VERSION': 'Версія протоколу',
    'NOTARIZED': 'Нотаріальні вузли',
    'BLOCKS': 'Блоків',
    'DIFFICULTY': 'Складність',
    'PAY_TX_FEE': 'Плата за транзакцію',
    'RELAY_FEE': 'Relay Fee',
    'ERRORS': 'Помилки',
    'ADD_NODE': 'Додати Вузол',
    'USE_THIS_SECTION': 'Використовуйте цей розділ, щоб перевірити, чи вказаний вузол IP, який ви хочете додати, вже активний як пір вашої монети:',
    'SELECT_COIN': 'Обрати Монету',
    'CHECK_NODES': 'Перевірити Вузли',
    'USE_THIS_SECTION_PEER': 'Використовуйте цей розділ, щоб додати пір IP для обраної монети:',
    'WALLET_BACKUP': 'Резервна копія Гаманця',
    'FIAT_CURRENCY': 'Fiat Currency',
    'EXPORT_KEYS': 'Експортувати Ключі',
    'ONLY_ACTIVE_WIF_KEYS': 'Тут буде показано лише WIF-ключі активного гаманця монети.<br>' +
                            'Ви можете використовувати ці WIF-ключі для імпорту в інші гаманці.',
    'PLEASE_KEEP_KEYS_SAFE': 'Будь ласка, тримайте ці ключі в безпеці та надійно.',
    'PASSPHRASE': 'Парольна фраза',
    'GET_WIF_KEYS': 'Отримати WIF-ключі',
    'IMPORT_KEYS': 'Імпортувати ключі',
    'IMPORT_KEYS_DESC_P1': 'Цей розділ дозволяє імпортувати приватний ключ усіх підтримуваних монет гаманця.',
    'IMPORT_KEYS_DESC_P2': 'Не обов\'язково мати цю монету в гаманці, для якого ви виконуєте процес імпорту приватного ключа.',
    'IMPORT_KEYS_DESC_P3': 'You\'ll also notice the private key you imported for one coin or chain will also be showing a new address in all other coin wallets\' receiving address section. ' +
               'It is normal.',
    'INPUT_PRIV_KEY': 'Вхідний приватний ключ',
    'IMPORT_PRIV_KEY': 'Імпорт приватного ключа',
    'EMPTY_PASSPHRASE_FIELD': 'Поле парольної фрази',
    'WALLET_RESCAN_FINISHED': 'Повторне сканування гаманеця закінчено',
    'ADDRESS_IMPORTED': 'Адреса імпортується',
    'ADDRESS_IMPORTED_RESCAN_IN_PROGRESS': 'Адреса імпортується. Кошик перезавантажується. Будь ласка, зачекайте, закінчення процесу.',
    'DEBUG_LOG': 'Налагодження',
    'DEBUG_LOG_DESC': 'Цей розділ дозволяє прочитати останні N рядків з файлу журналу налагодження.',
    'DEBUG_LOG_LINES': 'Введіть число рядків для читання',
    'TARGET': 'Target',
    'LOAD_DEBUG_LOG': 'Завантаження debug log',
    'REFRESH_FUNDS': 'Оновити фонди',
    'INFO': 'Інфо',
    'ENTER': 'Введіть',
    'ADDR_SM': 'адреса',
    'ACTIVATING': 'Активація',
    'QRCODE': 'Показати QR код',
    'SCAN_QR_CODE': 'Сканувати QR код',
    'SCAN_QRCODE_WEBCAM': 'Сканувати QR код через веб-камеру',
    'TOGGLE_ZERO_ADDRESSES': 'Toggle empty addresses',
    'NEXT_PAGE': 'Наступна сторінка',
    'PREVIOUS_PAGE': 'Попередня сторінка',
    'CREATE_INVOICE': 'Створити рахунок-фактуру',
    'CREATE_INVOICE_QR': 'Створити QR код рахунок-фактури',
    'QR_CONTENT': 'Вміст QR коду',
    'CHOOSE_RECEIVING_ADDRESS': 'Обрати адресу',
    'SAVE_AS_IMAGE': 'Зберегти як зображення',
    'OPEN_TRANSACTION_IN_EPLORER': 'Відкрити транзакцію в @template@ Explorer',
    'SWISSKNIFE': 'Підтримка',
    'SAFEVOTE': 'Safe Голосування',
    'TOOLS': 'Інструменти',
  },
  'ATOMIC': {
    'RAW_OUTPUT': 'Raw вивід',
    'SUBMIT': 'Відправити',
    'INPUT_PLACEHOLDER': 'addr, txid, blockash и т.д.',
    'SELECT_COMMAND': 'Обрати команду',
  },
  'ADD_COIN': {
    'SYNC_ONLY': 'Тільки синхронізація',
    'SAVE_SELECTION': 'Зберегти виділене',
    'LOAD_SELECTION': 'Завантажити виділене',
    'ACTIVATE_ALL': 'Активувати все',
    'ADD_ANOTHER_COIN': 'Додати ще монету',
    'ALREADY_ADDED': 'вже додано',
    'COIN_ALREADY_ADDED': 'Монета вже додана',
    'IN': 'в',
    'MODE': 'режим',
    'CRYPTO_CURRENCIES': 'Крипто валюти',
    'ASSETCHAINS': 'Assetchains',
    'FIAT_CURRENCIES': 'Фіатні валюти',
    'LITE': 'Lite',
    'LITE_MODE_DESC': 'Режим Lite не вимагає, завантаження ланцюжка блоків. Всі дані запитуються з серверів Electrum. Режим Lite має більш високу затримку в мережі в порівнянні зі звичайним режимом.',
  },
/*  'JUMBLR': {
    'PASSPHRASE': 'Кодовая фраза',
    'PAUSE': 'Пауза',
    'RESUME': 'Продолжить',
    'STOP': 'Стоп',
    'TO_SM': 'кому',
    'ABOUT': 'О Jumblr',
    'JUMBLR_FUNCTIONS': 'Jumblr выполняет все локально, что означает, не требуется посредник для запутывания Ваших средств. ' +
                        'Весь процесс у Вас под контролем.',
    'TIP': 'Подсказка',
    'TIP_DESC': 'для достижения максимальной анонимности Jumble node на выделенном сервере (ноутбук або VPS), используйте отдельный IP-адрес для основного узла Jumblr',
    'PUBLIC_NODE': 'Публичные ноды',
    'PRIVATE_NODE': 'Приватные ноды',
    'DEPOSIT_ADDRESS': 'Адрес пополнения',
    'SECRET_ADDRESS': 'Секретный адрес',
    'DEPOSIT_FUNDS': 'Deposit funds',
    'HOW_TO_USE': 'Как пользоваться Jumblr',
    'CREATE_DEPOSIT_ADDRESS': 'Создайте адрес пополнения',
    'CREATE_SECRET_ADDRESS': 'Создайте секретный адрес',
    'SEND_FUNDS_TO_DEPOSIT': 'Отправьте средства на deposit адрес',
    'PLEASE_WRITE_DOWN_PASSPHRASE': 'Введите Вашу парольную фразу Jumblr и храните её в безопаcном месте.',
    'THIS_IS_YOUR_MAIN_RECOVERY': 'Это Ваша основная парольная фраза для восстановления.',
    'ALL_JUMBLR_ADDRESSES_CAN_BE': 'Все адреса Jumblr могут быть восстановлены по ней.',
    'DONT_USE_SMART_EDITORS': 'не используйте интеллектуальные редакторы для хранения вашей кодовой фразы, поскольку они, как правило, добавляют дополнительные символы.<br>Это может привести к несоответствию парольной фразы с исходной кодовой фразой.',
    'PASSPHRASE_COPIED': 'Парольная фраза скопирована',
    'CREATE_JUMBLR_DEPOSIT_ADDRESS': 'Создайте Jumblr адрес пополнения',
    'YOUR_JUMBLR_DEPOSIT_ADDRESS': 'Ваш Jumblr адрес пополнения',
    'JUMBLR_SECRET_DESC_P1': 'Jumblr секретные адреса используются для заключительной z -> t транзакций.',
    'JUMBLR_SECRET_DESC_P2': 'Чтобы позволить более крупным учетным записям получать конфиденциальность, поддерживаются до 777 секретных адресов.',
    'JUMBLR_SECRET_DESC_P3': 'Когда активируется этап z -> t, выбирается случайный секретный адрес из списка активных секретных адресов.',
    'JUMBLR_SECRET_DESC_P4': 'Чтобы добавить ещё набор секретных адресов, введите количество адресов ниже. Кодовая фраза ниже точно такая же, как вы видели на предыдущем шаге.',
    'JUMBLR_SECRET_DESC_P5': 'Ваша Jumblr парольная фраза для восстановления секретных адресов будет иметь следующий шаблон',
    'JUMBLR_SECRET_DESC_P6': 'Где XXX любое число от 001 до 777',
    'NUMBER_OF_SECRET_ADDR': 'Количество секретных адресов',
    'CREATE_JUMBLR_SECRET_ADDR': 'Создать Jumblr секретный адрес(а)',
    'SHOW_ADDRESS_LIST': 'Показать список адресов',
    'DEPOSIT_FORM_P1': 'Используйте форму ниже, чтобы отправить средства на Ваш jumblr адрес пополнения.',
    'DEPOSIT_FORM_P2': 'Вы так же можете отправить средства на jumblr адрес пополнения с любого внешнего сервиса або другого кошелька.',
    'IMPORT_SECRET_ADDRESS': 'Импортировать секретный адрес',
    'CHECK_FUNDS': 'Проверить средства',
    'SECRET_REGEN_DESC_P1': 'Для импорта секретного адреса Jmbrl, введите Вашу кодовую фразу Jumblr которую Вы получили при настройке Публичного узла.',
    'SECRET_REGEN_DESC_P2': 'Пример кодовой фразы',
    'SECRET_REGEN_DESC_P3': 'В форме ниже будет «регенерирован» секретный адрес Jumblr на основе введённой кодовой фразы.',
    'SECRET_REGEN_DESC_P4': 'После этого последнего шага ожидайте увидеть средства, обработанные и зачисленные на ваш адрес в течении двух дней.',
    'IMPORT_JUMLR_SECRET_ADDRESSES': 'Импорт секретных адресов Jumblr',
    'SHOW_ADDRESS_LIST': 'Показать список адресов',
    'NOTICE': 'ЭКСПЕРИМЕНТАЛЬНАЯ ВЕРСИЯ! ТОЛЬКО ДЛЯ ТЕСТИРОВАНИЯ!',
    'DESCRIPTION': 'Функция Jumblr экспериментальна и на данный момент включена только для тестирования и отладки. ' +
                   'Если вы участвуете в тестировании этой функции, используйте текущую версию Jumblr только с небольшими суммами.',
    'NEED_NATIVE': 'Требуется Нативный режим Safecoin',
    'TO_USE_JUMBLR': 'Чтобы использовать функцию Jumblr, вам необходимо активировать Safecoin в Нативном режиме.',
    'IF_YOU_ALREADY_RUNNING': 'Если вы уже используете Safecoin в режиме Basilisk або Полный Режим, закройте кошелек и снова перезапустите, чтобы запустить Safecoin в Нативном Режиме.',
    'THIS_SCREEN_DOESNT_REFRESH': 'Это окно не обновляется автоматически. ' +
                                  'Вам нужно нажать кнопку «Обновить» в правом верхнем углу окна, чтобы получить последние данные Jumblr.',
    'FEW_SECURITY_NOTES': 'Несколько примечаний по безопасности для вашей конфиденциальности и анонимности средств',
    'FEW_SECURITY_NOTES_DESC1': 'Jumblr адреса - это ваши личные адреса.',
    'FEW_SECURITY_NOTES_DESC2': 'НИКОМУ НЕ ПОКАЗЫВАЙТЕ Ваши Jumblr адреса.',
    'FEW_SECURITY_NOTES_DESC3': 'Jumblr адрес - это как ВАШ ПАРОЛЬ. Храните его в безопасности, надёжно и скрытно.',
    'FEW_SECURITY_NOTES_DESC4': 'Только ВЫ должны знать Ваши Jumblr адреса. Никто больше.',
    'FEW_SECURITY_NOTES_DESC5': 'Раскрытие Ваших Jumblr  адресов и совместное использование с кем-нибудь лишает смысла в использовании Jumblr, Ваши средства и транзакции не будут больше приватными.',
    'ACCESS_JUMBLR_FUNDS': 'Как получить доступ к своим Jumblr средствам',
    'ADDRESS_ACCESSIBLE_EASILY': 'Ваши Jumblr адреса легко доступны. Например, вы вошли в свой кошелек с кодовой фразой',
    'TO_ACCESS': 'Чтобы получить доступ к своим ресурсам Jumblr Вам необходимо выйти.',
    'START_SAFE': 'Запустить Safecoin в режиме Full або Basilisk.',
    'WORD_JUMBLR': 'Затем добавьте слово \'jumblr\' перед вашей фразой.',
    'SMALL_LETTERS': '"jumblr" все буквы маленькие .',
    'WHITE_SPACE': 'Пробел в конце "jumblr ".',
    'PER_EXAMPLE': 'Таким образом, согласно этому примеру, ваши Jumblr Адреса доступны:',
    'LOGIN_WITH_JUMBLR': 'Вы авторизовались с Вашей Jumblr кодовой фразой для доступа к Вашими Jumblr-средствам, и можете использовать их, так же как и любой адрес в кошельке.',
    'AGAIN_DONT_SHARE': 'И снова, НЕ ДЕЛИТЕСЬ СВОИМ JUMBLR АДРЕСОМ НИ КЕМ.',
    'USING_JUMBLR': 'Использование Jumblr',
    'RUN_SAFE': 'Запустите Safecoin в Native режиме',
    'LOGIN_SAFE': 'Авторизуйтесь используя свою кодовую фразу',
    'GO_TO': 'Откройте закладку Jumblr',
    'FIND_DEPOSIT_ADDR': 'Найдите там Ваш Депозитный адрес монеты, средства которой Вы хотите анонимизировать. (На начальном этапе поддерживается только SAFE. Поддержка BTC будет доступна в следующих версиях)',
    'YOU_SEND_FUNDS': 'Вы отправляете Ваши средства на Депозитный адрес.',
    'KEEP_WALLET_OPEN': 'Держите Ваш кошелёк открытым',
    'IMPORTANT_FUNDS': '[ВНИМАНИЕ] Средства обрабатываются лотами кратно 100 SAFE, 1000 SAFE, and 10000 SAFE.',
    'LARGE_LOT': 'Лоты большего размера обрабатываются раньше, чем меньшего.',
    'EG': 'Например, вы отправили 1393 SAFE на SAFE Deposit Address.<br>' +
          'Сперва будут обработаны 1000 SAFE<br>' +
          'затем 100 SAFE<br>' +
          'ещё 100 SAFE<br>' +
          'и ещё 100 SAFE',
    '93_SAFE': '93 SAFE останутся на Депозитном адресе.',
    'TO_CLEAR_THEM': 'Для обработки Вам необходимо прислать ещё 7 SAFE на Ваш SAFE Депозитный адрес.',
    'WHEN_IT_TOTALS': 'Когда наберётся сумма минимального лота 100 SAFE, запустится процесс на Вашем SAFE Jumblr Адресе.',
    'JADDR': 'Jumblr Адрес',
    'BTC_DEPOSIT': 'BTC Deposit',
    'SHOW_HIDE': 'Показать/Скрыть',
    'HIDDEN': 'Скрыто по соображениям безопасности.',
    'SAFE_DEPOSIT': 'SAFE Deposit',
    'JSTATUS': 'Jumblr Статус',
    'RESULT': 'Результат',
    'DEPOSITED': 'Deposited',
    'PUB_TO_PRIV': 'Публичный на Приватный',
    'PRIV_TO_PRIV': 'Приватный на Приватный',
    'PRIV_TO_PUB': 'Приватный на Публичный',
    'FINISHED': 'Завершено',
    'PENDING': 'В ожидании',
    'ERROR': 'Ошибка',
  },*/
  'DASHBOARD': {
    'SHOW_ALL_ADDR': 'Показати всі адреси',
    'RPC_CONN_FAILURE': 'Не вдалося встановити з\'єднання з RPC!',
    'REMOVE': 'Видалити',
    'STOP': 'Стоп',
    'SOFT_LOGOUT': 'Мягкий вихід',
    'COMPLETE_LOGOUT': 'Повний вихід',
    'GENERATE_SM': 'генерувати',
    'RECEIVE_ADDR_COPIED': 'адреса скопійований в буфер обміну',
    'SERVER_SM': 'сервер',
    'IS_UNREACHABLE': 'недоступний',
    'SERVER_SET_TO': 'сервер встановлений на',
    'SPV_AUTO_SWITCH': 'Спроба переключитися на інший сервер',
    'HOW_TO_SWITCH_MANUALLY': 'Як перемикатися вручну',
    'SELECT_ADDRESS': '- Обрати адресу -',
    'SEND_TOADDR_REQ': 'Вказати адреса отримувача.',
    'SEND_FROMADDR_REQ': 'Вказати адресу відправки.',
    'SEND_AMOUNT_REQ': 'Введіть суму для відправки.',
    'SEND_FEE_REQ': 'Переконайтеся, що Ви врахували комісію.',
    'SEND_TOTAL_REQ': 'Переконайтеся, що сума і комісія введені для підрахунку підсумкового значення.',
    'SEND_TX_PROGRESS': 'Транзакція в процесі. Деталі транзакції будуть відображені тут після обробки.',
    'SUBTRACT_FEE': 'Відняти комісію з суми відправки',
    'UNKNOWN': 'Невідомий',
    'IN': 'IN',
    'OUT': 'OUT',
    'MINED': 'Mined',
    'IMMATURE': 'Незрілі',
    'ZADDR_NOT_LISTED': 'Z Адреса не відображаються гаманцем',
    'ADDR_COPIED': 'Адреса скопійована',
    'QR_ERR_NO_VIDEO_DEVICE': 'Помилка: пристроїв введення відео, не знайдено!',
    'QR_ERR_UNKNOWN': 'Помилка: невідома помилка!',
    'SPV_CONN_ERROR': 'Помилка підключення!',
    'SPV_CONN_ERROR_P1': 'Перейдіть в «Налаштування», виберіть вкладку «Список серверів SPV», виберіть новий сервер і натисніть «ОК».',
    'FAILED_TX_INFO': 'Збій транзакції або процес переіндексації триває. Невірні транзакції зазвичай відхиляються через деякий час, в результаті чого ваші кошти повертаються.',
    'SPV_CLAIMED_INTEREST': 'Нараховані відсотки',
    'CLAIM_INTEREST_HELPER_BAR_P1': 'У Вас набігло',
    'CLAIM_INTEREST_HELPER_BAR_P2': 'до зарахування',
    'CLAIM_INTEREST_HELPER_BAR_P3': 'Зарахувати',
    'CLAIM_INTEREST_HELPER_BAR_ALT_P1': 'У вас немає відсотків до зарахування',
    'CLAIM_INTEREST_HELPER_BAR_ALT_P2': 'Перевірити UTXO',
    'SEARCH': 'Пошук',
    'CURRENT_BLOCK_SM': 'поточний блок',
  },
  'TOASTR': {
    'INCORRECT_WIF': 'Не вірний формат ключа (WIF)',
    'ERROR': 'Помилка',
    'FAILED_TO_VERIFY_ADDR': 'Не вдалося перевірити адресу',
    'COIN_UNABLE_TO_STOP': 'Неможливо зупинити @template@. Спробуйте знову.',
    'COIN_IS_STOPPED': 'зупинений',
    'COIN_IS_REMOVED': 'видалений',
    'JUMBLR_RESUMED': 'Jumblr продовжений',
    'JUMBLR_PAUSED': 'Jumblr призупинений',
    'DATADIR_UNABLE_TO_CLEAR': 'Неможливо очистити',
    'DATADIR_CLEARED': 'каталог даних очищений',
    'PORT_IS_TAKEN': 'Порт @template@ вже зайнятий!',
    'ERROR_STARTING_DAEMON': 'Помилка запуску служби @template@.',
    'SAFECOIN_DATADIR_INVALID': 'Шлях до каталогу Safecoin невірний.<br>Це повинен бути абсолютний шлях до існуючої папки, яка не містить пробілів і / або будь-яких спеціальних символів.',
    'SAFECOIN_DATADIR_NOT_DIR': 'Шлях до каталогу Safecoin не є каталогом.<br>Це повинен бути абсолютний шлях до існуючої папки, яка не містить пробілів і / або будь-яких спеціальних символів.',
    'INVALID_ADDRESS': 'Не вірний @template@ адрес',
    'RESTART_SAFEWALLET_WITH_REINDEX_PARAM': 'Перезапустіть Safewallet і запустіть Safecoin з параметром -reindex',
    'JUMBLR_DEPOSIT_ADDRESS_SET': 'Jumblr адреса поповнення встановлена',
    'JUMBLR_SECRET_ADDRESSES_IMPORTED': 'Jumblr секретні адреси імпортовані',
    'JUMBLR_SECRET_ADDRESS_IMPORTED': 'Jumblr секретна адреса імпортована',
    'JUMBLR_WRONG_PASSPHRASE': 'Надана парольна фраза має неправильний формат',
    'JUMBLR_SECRET_ADDRESS_SET': 'Jumblr секретна адреса встановлена',
    'JUMBLR_SECRET_ADDRESSES_SET': 'Jumblr секретні адреси встановлені',
    'ENTER_CORRECT_ADDR_COUNT': 'Введіть правильне значення кількості адрес',
    'TXID_COPIED': 'ID Транзакції скопійований',
    'CLAIM_INTEREST_BALANCE_SENT_P1': 'Ваш повний баланс відправлено на адресу',
    'CLAIM_INTEREST_BALANCE_SENT_P2': 'Перевірте свій новий баланс через кілька хвилин.',
    'SETTINGS_RESET': 'Налаштування скинуті до стандартних значень',
    'SETTINGS_SAVED': 'Налаштування збережені',
    'TRANSACTION_FAILED': 'Не вдалося виконати транзакцію',
    'WALLET_NOTIFICATION': 'Сповіщення гаманця',
    'ACCOUNT_NOTIFICATION': 'Сповіщення акаунту',
    'COIN_NOTIFICATION': 'Сповіщення монети',
    'TX_NOTIFICATION': 'Сповіщення транзакції',
    'SERVICE_NOTIFICATION': 'Сповіщення служби',
    'LOGIN_NOTIFICATION': 'Сповіщення входу',
    'SETTINGS_NOTIFICATION': 'Сповіщення налаштування',
    'RECADDR_UPDATED': 'Список адрес отримання оновлений',
    'SWITCHED_TO': 'переключено в',
    'MODE': 'Режим',
    'TX_SENT': 'Транзакція відправлена',
    'TX_SEND_ERR': 'Не вдалося виконати транзакцію',
    'LOOKS_LIKE': 'Схоже',
    'ALREADY_RUNNING': 'вже запущений',
    'STARTED_IN': 'Запущено ',
    'SAFECOIN_ERR': 'Неможливо запустити Safecoind',
    'SIGNED_TX_GENERATED': 'Підписана транзакція згенерована',
    'SIGNED_TX_GENERATED_FAIL': 'Генерація підписаної транзакції не вдалася',
    'SENDING_TX': 'Відправляємо транзакцію в мережу',
    'SIGNED_TX_SENT': 'Підписана транзакція успішно відправлена',
    'GETTING_TXID_INFO': 'Отримання txid для поновлення даних коштів',
    'REFRESHING_FUNDS': 'Оновлення коштів гаманця',
    'TX_FAILED': 'Вихідна транзакція не вдалася. Будь ласка, перевірте сторінку відправки для деталей.',
    'TX_SENT_ALT': 'Транзакція успішно відправлена. Перевірте сторінку відправки для деталей.',
    'COIN_STARTED': 'монета запущена',
    'ADDR_ALREADY_REG': 'адреса вже зареєстрована в мережі.',
    'REG': 'Зареєстрований',
    'REG_ADDR': 'адреса в мережі.',
    'REG_ADDR_FAILED': ' реєстрація не вдалася. Будь ласка повторіть.',
    'INVALID_QUERY': 'Невірний запит',
    'TRY_AGAIN': 'Будь ласка повторіть.',
    'ADDR_ISNT_REG': 'Адресу не зареєстрований в мережі. Будь ласка, зареєструйтесь',
    'INVALID_QUERY_ALT': 'Невірний запит. Будь ласка повторіть.',
    'VALIDATION_SUCCESS': 'Успішна перевірка в мережі',
    'SAFE_NATIVE_CON_ERROR': 'Помилка підключення. Зовнішній гаманець запущений?',
    'LOGIN_SUCCESSFULL': 'Авторизація вдалася',
    'OPPS': 'От чорт ... Щось пішло не так!',
    'INVALID_PASSPHRASE': 'Невірна парольна фраза. Переконайтеся, що ваша парольна фраза вірна або створіть новий гаманець.',
    'WALLET_CREATED_SUCCESFULLY': 'Гаманець успішно створений',
    'LOGOUT_SUCCESSFULL': 'Успішний вихід',
    'WALLET_LOCKED': 'Гаманець успішно заблоковано',
    'PRIV_KEY_IMPORTED': 'Приватний Ключ успішно імпортовано!',
    'PRIV_KEY_NOT_IMPORTED': 'Приватний ключ не імпортовано.',
    'ADDED_TO': 'додано в',
    'SUCCESSFULLY': 'Успішно',
    'COIN_SELECTION': 'Вибір монети',
    'SELECTION_NOT_FOUND': 'Локальний список монет не знайдено',
    'AWAITING_TX_RESP': 'Очікування відповіді даних транзакції',
  },
  'COIN_WALLETS': {
    'TX_FAILED': 'Транзакція не вдалася',
    'TX_SUCCESS': 'Успішна транзакція',
    'TX': 'Транзакція',
  },
  'IAPI': {
    'PUBLIC_SM': 'public',
    'CON_STATUS': 'Статус підключення',
  },
  'SAFE_NATIVE': {
    'SELECT_ADDRESS': 'Виберіть Публічну або Приватну адресу',
    'SELECT_ADDRESS_ALT': 'Виберіть Публічну або Приватну адресу SAFE',
    'PRIVATE': 'приватний',
    'NEW_ADDR_GENERATED': 'Нову адресу успішно згенеровано',
    'QUEUED': 'В черзі',
    'PLEASE_REFRESH': 'Натисніть кнопку оновити приблизно через хвилину, щоб побачити оновлений статус',
    'EXECUTING': 'Виконується',
    'FAILED': 'Не вдалося',
    'SUCCESS': 'Успішно',
    'MESSAGE': 'Повідомлення',
    'EXECUTION_SECONDS': 'Час виконання',
    'WAIT_UNTIL_SYNCED': 'Історія транзакцій недоступна під час синхронізації',
    'TXID': 'ID Транзакції',
    'ZCASH_PARAMS_MISSING': 'Zcash params відсутні або неповні:',
    'ZCASH_PARAMS_MISSING_ROOT_DIR': '- відсутня коренева папка',
    'ZCASH_PARAMS_MISSING_PROVING_KEY': '- відсутній ключ підтвердження',
    'ZCASH_PARAMS_MISSING_VERIFYING_KEY': '- відсутній ключ перевірки',
    'ZCASH_PARAMS_MISSING_PROVING_KEY_SIZE': '- розмір ключа підтвердження некоректний',
    'ZCASH_PARAMS_MISSING_VERIFYING_KEY_SIZE': '- розмір ключа перевірки некоректний',
  },
  'LOGIN': {
    'OR_USE_A_SHORTCUT': 'або скористайтеся ярликом',
    'PIN_LOGIN_INFO': 'Ви можете увійти ввівши парольну фразу або PIN',
    'QUICK_ACCESS': 'Швидкий доступ',
    'PWD_REQ': 'Пароль обов\'язковий.',
    'WALLET_SEED_REQ': 'Парольна фраза гаманця обов\'язкова.',
    'SAVED_WALLET_SEED': 'Ви зберегли Вашу парольну фразу від гаманця?',
    'SEED_MAKE_SURE_BACKUP': 'Переконайтеся, що у Ви зберегли парольну фразу. Без неї ви не зможете отримати доступ до свого гаманця в майбутньому!',
    'YES_I_BACKUP': 'Так, я впевнений в тому, що зробив резервну копію.',
    'WALLET_LOCKED_LOGIN': 'Гаманець заблокований. Будь ласка, війдіть.',
    'CANCEL': 'Відміна',
    'UNLOCK': 'Розблокувати',
    'SIGN_IN': 'Вхід',
    'WELCOME': 'Вітаємо!',
    'ENTER_VALUE_AGAIN': 'Будь ласка, введіть те ж значення знову',
    'CUSTOM_WALLET_SEED': 'Власна парольна фраза',
    'MUST_ENTER_SEED': 'Вам потрібно ввести парольну фразу',
    'INVALID_SEED': 'Невірна парольна фраза',
    'SEED_NOT_OF_TYPE': 'Парольна фраза не має тип',
    'IGUANA_SEED': 'Iguana (256 bits)',
    'WAVES_SEED': 'Waves',
    'NXT_SEED': 'NXT',
    'SEED_COPIED': 'Парольна фраза скопірована',
    'SEED_SUCCESSFULLY_COPIED': 'Парольна фраза успішно скопірована',
    'ENCRYPT_SEED': 'Зашифрувати вхідну парольну фразу',
    'PUBKEY': 'публічний ключ',
    'ENCRYPT_KEY': 'Зашифрувати ключ',
    'DECRYPT_KEY': 'Розшифрувати ключ'
  },
  'SIDEBAR': {
    'EDEX_MOTTO': 'Найбільш безпечний, простий і нативний децентралізований обмін',
    'JUMBLR_MOTTO': 'Безпечний, нативний і децентралізований анонимайзер монети',
  },
  'SETTINGS': {
    'DAEMON_PORTS': 'Порти сервісу',
    'KEY_IS_NOT_FOUND': 'Ключ не знайдено',
    'ADDRESSES_SM': 'адреси',
    'ACCOUNT_SM': 'аккаунт',
    'ACCOUNTS_SM': 'аккаунти',
    'GET_KEY': 'Отримати ключ',
    'DATADIR_DELETE_PROMPT': 'Ви впевнені, що хочете очистити каталог з даними @template@?',
    'YES': 'Так',
    'NO': 'Ні',
    'KEEP': 'Зберегти',
    'DELETE': 'Видалити',
    'COIND_DELETING': 'Видаляємо @template@ дані..',
    'COIND_DATADIR_CLEAR_P1': 'Попередження: наступна форма знищить всі дані про нативний клієнт монети!',
    'COIND_DATADIR_CLEAR_P2': 'Нічого не чіпайте, якщо ви не знаєте, що робите.',
    'GET_KEYS': 'Отримати ключі',
    'FETCHING_KEYS': 'Отримання ключів',
    'SEARCH_KEY_PATTERN': 'Шукати патерн ключа',
    'ADDRESS': 'Адреса',
    'KEYS_SM': 'ключі',
    'FOUND': 'Found',
    'PICK_A_COIN': 'Вкажіть монету',
    'CLEAR_NATIVE_DATADIR': 'Очистити папку нативного клієнта монети',
    'KEYS_SM': 'ключі',
    'KEYS_CAP': 'Ключі',
    'BIP39_DISC': 'Повідомлення про апаратні гаманці: використовуючи цю форму, ви підтверджуєте ризик викриття вашої парольної фрази',
    'BIP39_DESC_P1': 'Опис: Форма нижче дозволяє шукати публічний ключ на основі діапазону обраних комбінацій (число акаунтів * глибина шляху адреси аккаунта).',
    'BIP39_DESC_P2': 'Програма може "зависнути" на кілька секунд під час процедури пошуку.',
    'SHOW_APP_RUNTIME_LOG': 'Показати журнал (log) програми',
    'WRONG_PASSPHRASE': 'Помилкова парольна фраза!',
    'SPV_SERVER_LIST_DESC': 'Вибір списку серверів доступний тільки для активних монет, у яких є більше одного активного підключення.',
    'SPV_SERVERS': 'список серверів SPV',
    'SPV_SINGLE_SERVER_NOTICE': 'Тільки один сервер electrum доступний. SPV перевірка приходить від того ж сервера, що і розсилає дані.',
    'SAFE_MAIN_SYNC_ONLY': 'SAFE main sync only',
    'RPC_FETCH_ONLY_DESC': 'Отримувати тільки дані синхронізації. Пропустити будь-які інші запити, які можуть погіршити швидкість синхронізації.',
    'RESET_TO_DEFAULT': 'Відновити значення за замовчуванням',
    'PROGRESS': 'Виконання',
    'SUPPORT': 'Підтримка',
    'SUPPORT_TICKETS': 'Заявки служби підтримки',
    'GET_SLACK_INVITE': 'Отримати запрошення',
    'ADDRESS_LIST': 'Адреса',
    'WIF_KEY_LIST': 'ключ (WIF)',
    'CLI_RESPONSE': 'відповідь CLI',
    'PASSPHRASE_REQ': 'Потрібна парольна фраза.',
    'SAVE_APP_CONFIG': 'Зберегти конфігурацію програми',
    'CONFIG_RESTART_REQUIRED': 'Будь-які зміни в конфігурації програми вимагають перезапуску програми!',
    'APP_CONFIG': 'Налаштування програми',
    'APP_INFO': 'Інформація програми',
    'APP_RELEASE': 'Реліз програми',
    'NAME': 'Ім\'я',
    'VERSION': 'Версія',
    'SYS_INFO': 'Системна інформація',
    'ARCH': 'Архітектура',
    'OS_TYPE': 'Тип ОС',
    'OS_PLATFORM': 'Платформа ОС',
    'OS_RELEASE': 'Реліз ОС',
    'CPU': 'CPU',
    'CPU_CORES': 'Ядра CPU',
    'MEM': 'Пам\'ять',
    'LOCATIONS': 'Розташування',
    'CACHE': 'Кеш',
    'CONFIG': 'Конфігурація',
    'BIN': 'Bin',
    'DIR': 'Папка',
    'ADD_PEER_IP': 'Додати IP піра',
    'APP_SESSION': 'Сесія програм',
    'EXPORT_KEYS_NOTE': 'Примітка: важливо, щоб ви надали ту ж кодову фразу, яку ви використовували для входу в гаманець!',
  },
  'TX_INFO': {
    'ADDRESS': 'адреса',
    'AMOUNT': 'кількість',
    'CATEGORY': 'категорія',
    'CONFIRMATIONS': 'підтвердження',
  },
  'ZCPARAMS_FETCH': {
    'DOWNLOADING_ZCASH_KEYS': 'Завантажуємо ключі Zcash',
    'BOTH_KEYS_VERIFIED': 'Ключі Zcash завантажені і перевірені!',
    'PLEASE_RESTART': 'Будь ласка, перезапустіть пристрій.',
    'ZCPARAMS_VERIFICATION_ERROR_P1': 'Zcash param',
    'ZCPARAMS_VERIFICATION_ERROR_P2': 'помилка перевірки!',
    'ZCPARAMS_FETCH': 'Отримання ZCash Params',
    'SELECT_ZCPARAMS_SOURCE': 'Виберіть джерело завантаження ключів Zcash',
    'DOWNLOAD': 'Завантажити',
  },
  'SEND': {
    'SELF': 'Мені',
    'ALL': 'Все',
    'BAD_TXN_SPENT_ERR1': 'Ця конкретна помилка може статися в наступних випадках:',
    'BAD_TXN_SPENT_ERR2': 'Ваш годинник на комп\'ютері не налаштований належним чином',
    'BAD_TXN_SPENT_ERR3': 'SPV сервер тимчасово не синхронізований. Спробуйте перейти на інший.',
    'BAD_TXN_SPENT_ERR4': 'Подвійні витрати, якщо ви тільки що зробили іншу транзакцію',
    'MIN_AMOUNT_IS': 'мін. @template@ сума є',
    'AMOUNT_IS_TOO_SMALL': 'Сума @template@ занадто мала',
    'MAX_AVAIL_BALANCE': 'макс. доступний баланс - це',
    'TXID_COPIED': 'TXID скопійовано в буфер обміну',
    'RESULT': 'Результат',
    'PROCESSING_TX': 'Транзакція в процесі',
    'TRANSACTION_ID': 'ID транзакції',
    'SUCCESS_SM': 'успішно',
    'WARNING': 'Попередження',
    'WARNING_SPV_P1': 'дані вашого гаманця перевірені тільки одним сервером!',
    'WARNING_SPV_P2': 'Якщо ви все ще хочете продовжити, натисніть «Підтвердити».',
    'SPV_VERIFYING': 'Перевірка даних транзакції',
    'PROCESSING_REQ': 'Обробка запитів',
    'LOCKED_PLEASE_WAIT': 'Заблоковано, будь ласка, зачекайте',
    'UPDATE': 'Оновити',
    'SELECT_T_OR_Z_ADDR': 'Виберіть Публічну або Приватну (z) адресу',
    'ENTER_T_OR_Z_ADDR': 'Виберіть Публічну або Приватну адресу',
    'ENTER_ADDRESS': 'Введіть адресу',
    'AWAITING': 'Чекає у черзі',
    'PROCESSING': 'Обробка',
    'ERROR_CODE': 'Код помилки',
    'WAITING': 'Очікування',
    'PROCESSING_TRANSACTION': 'Обробляємо транзакцію',
    'NOTE_IT_WILL_TAKE': 'Увага: для завершення транзакції може знадобитися кілька хвилин',
    'ENTER_AN_ADDRESS': 'Введіть адресу',
    'YOU_PICKED_OPT': 'Ви вибрали опцію',
    'PLEASE_WAIT': 'Будь ласка зачекайте',
    'SEND_TO_ADDRESS_MIN_LENGTH': 'Адреса відправки повинен бути мінімум 34 символи',
    'AMOUNT_POSITIVE_NUMBER': 'Кількість повинна бути більше нуля',
    'FEE_POSITIVE_NUMBER': 'Комісія повинна бути більше нуля',
    'TOTAL_AMOUNT_POSITIVE_NUMBER': 'Разом (кількість-комісія) має бути більше нуля',
    'INSUFFICIENT_FUNDS': 'Для здійснення цієї транзакції у Вас недостатньо коштів',
    'SELECT_SOURCE_ADDRESS': 'Вкажіть адресу джерело (Від)',
    'QR_COIN_MISMATCH_MESSAGE_IMPORT_COIN': 'QR-код містив монету ',
    'QR_COIN_MISMATCH_MESSAGE_ACTIVE_COIN': '. У Вас ',
    'QR_COIN_MISMATCH_MESSAGE_END': ' Будь ласка, переконайтеся що у Вас активна та ж сама монета, яку Ви хочете імпортувати!',
    'QR_COIN_MISMATCH_TITLE': 'Монети не збігаються',
    'SEND_NATIVE_SYNC_WARNING': 'Ваш гаманець не повністю синхронізований! Будь ласка, дочекайтеся 100% завантаження.',
  },
/*  'FIAT_CURRENCIES': {
    'AUD': 'Australian Dollar (AUD)',
    'BRL': 'Brazilian Real (BRL)',
    'GBP': 'British Pound (GBP)',
    'BGN': 'Bulgarian Lev (BGN)',
    'CAD': 'Canadian Dollar (CAD)',
    'HRK': 'Croatian Kuna (HRK)',
    'CZK': 'Czech Koruna (CZK)',
    'CNY': 'Chinese Yuan (CNY)',
    'DKK': 'Danish Krone (DKK)',
    'EUR': 'Euro (EUR)',
    'HKD': 'Hong Kong Dollar (HKD)',
    'HUF': 'Hungarian Forint (HUF)',
    'INR': 'Indian Rupee (INR)',
    'IDR': 'Indonesian Rupiah (IDR)',
    'ILS': 'Israeli Shekel (ILS)',
    'JPY': 'Japanese Yen (JPY)',
    'KRW': 'Korean Won (KRW)',
    'MYR': 'Malaysian Ringgit (MYR)',
    'MXN': 'Mexican peso (MXN)',
    'NZD': 'New Zealand Dollar (NZD)',
    'NOK': 'Norwegian Krone (NOK)',
    'PHP': 'Philippine Peso (PHP)',
    'PLN': 'Polish Zloty (PLN)',
    'RON': 'Romanian Leu (RON)',
    'RUB': 'Russian Ruble (RUB)',
    'SGD': 'Singapore Dollar (SGD)',
    'ZAR': 'South African Rand (ZAR)',
    'SEK': 'Swedish Krona (SEK)',
    'CHF': 'Swiss Franc (CHF)',
    'THB': 'Thai Baht (THB)',
    'TRY': 'Turkish Lira (TRY)',
    'USD': 'US Dollar (USD)',
  },*/
  'ASSETCHAINS': {
    'SAFE': 'SafeCoin (SAFE)',
    'BTCZ': 'BitcoinZ (BTCZ)',
    'ANON': 'ANON (ANON)',
    'ZCL': 'ZClassic (ZCL)',
    'XSG': 'SnowGem (XSG)',
  },
 /* 'DEX': {
    'GEN_NEW_PASSPHRASE': 'Генерировать новую кодовую фразу',
    'LOGIN': 'Войти',
    'BACKUP_PASSPHRASE_P1': 'Сохраните  вашу кодовую фразу',
    'BACKUP_PASSPHRASE_P2': 'она не может быть восстановлена!',
    'ESTIMATED_BALANCE': 'Предполагаемый баланс',
    'TRADE_HISTORY_SM': 'история операций',
    'ELECTRUM_MODE': 'Electrum режим',
    'NATIVE_MODE': 'Нативный режим',
  },*/
};
